UT-210: Rebuilding of the code structure for Cliptool.
tv2/casparcg-cliptool pull request #81
Opened 2023-03-07 09:45 UTC by andr9528

2023-03-17 14:00 UTC, andr9528 commented
If any horses are found let me know. In that case i have propably missed renaming something back to it correct name, while doing the renaming.

2023-03-21 11:13 UTC, LindvedKrvang requested changes
We need to have a chat about folder structure of components.

All files are formatted as camelCased. They should to be kebab-cased.

You are overly fond of ternaries. They are good, but you are nesting them (which is not good) and using them to do complex stuff inside them (also not good). 
You are using ternaries a lot in the JSX where the else clause is returning nothing. React has another way of doing this - I have shown that in my comments.

There are a lot of comments that serve no purpose and should be removed. I have far from made a comment on all of them (I assume they were added before you started working on the codebase, but they should nonetheless be deleted)

There are lots of places where you use `String.join(' ')` where you should use simple interpolation instead. You are mainly doing this when creating your `className` variable. I have only commented on it once, but it applies for all places you this.

You have created a "one thing does all" component in form of your SettingsInput. This is a big no-go and violation of SRP

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/app.tsx
> +//CSS files:
I know you didn't add these comments, but they should be removed. They are allready out of date. The comment specifies `files` in plural, but only one css file is being imported and it's directly followed by other imports (some which are components, which makes the `components` comment in the important redundant as well)

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/app.tsx
> +                        ? <Thumbnail/>
As a rule of thumb, don't nest ternaries.
Also, when your ternaries are this small then 
```
specificChannel ? <Thumbnail /> : <Tabs />
```
is just as readable and takes up less space than
```
specificChannel 
  ? <Thumbnail /> 
  : <Tabs />
```

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/footer/operationModeEditVisibilityFooter.tsx
>  function resetOperationMode(): void {
Minor thing about the order in which functions appears in a file:

When you read a book you expect the first sentence to be at the top-left of the page and the second sentence to immediatly follow it. The same principle apply when ordering functions. You want to read the most relevant thing first.

In this case you are in `OperationModeEditVisibilityFooter.tsx` which is a component so the first should be the code for the component i.e. `export function OperationModeVisibilityFooter()` and then the next thing should be the first function that it calls.

So the structures becomes like this:
```
export functionA() {
  functionB()
  functionC()
}

functionB() {
  functionD()
}

functionD() {...}

functionC() {...}
```

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/header/header.tsx
> +//CSS files:
There are imports of components where this comments says they should be css files. This comment should be deleted.

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/header/header.tsx
> +                    ''
You are returning nothing here and in JSX then a ternary is not the right tool.
You can simply write:
```
<div>
  {reduxState.appNav.selectView === 0 && (
    // Your HTML here
  )}
</div>
```

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/header/header.tsx
> +            ) : null}
Same comment as above. Ternary is not the right tool here

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/header/headerButtons.tsx
> +        ''
Again, don't use ternary for this in JSX

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/header/headerButtons.tsx
> +function handleLoopStatus(activeTab: number): void {
`handleLoopStatus` doesn't tell anything about what the function does rather who calls the function. A function should be agnostic about who calls it.
A more apt name for this function would be `emitSetLoopStateEvent()`.

If you want keep the naming convention `handleX` or `xClicked` etc then you must call another function that has an apt name for what it does, i.e:
```
function handleLoopStatus(...) {
  emitSetLooptStatusEvent(...)
}
```
This comment applies for all your `handleX` methods,

I will highly encourage you stop using the `handleX` naming convetion. If you are not convinced then look at the following snippet of code and tell me what happens when the button is clicked:
```
<button onClick="handleOkButtonClicked">Ok</button>
```
and now look at this snippet and tell me what happens when the button is clicked:
```
<button onClick="closeConfirmationModal()">Ok</button>
```

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/header/time.tsx
> +        cleanTallyFile = mediaService.getCleanSelectedFile(settingsOutput)
Why is this in a try-catch? It looks like `getCleanSelectedFile` is just doing string manipulations

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/header/toggleButton.tsx
> +export default function ToggleButton(props: ToggleButtonProps): JSX.Element {
You have called this `ToggleButton`, but the actual logic for toggling is outside of the component and must be implemented everytime you use this component. 
So in fact this is not a ToggleButton, it's just a button that changes a CSS class depending on a boolean flag (and boolean flags are a bad practice/code smell)

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/header/toggleButton.tsx
> +export default function ToggleButton(props: ToggleButtonProps): JSX.Element {
Also components like this should be in a `shared` folder, but it looks like we need a talk about folder structure

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/settings/outputs.tsx
> +                            return <SingleOutput configChannel={item} index={index} output={props.settings.outputs[index]} key={index} setOutput={setOutput}/>
Don't use `index` for `key`. React won't be able to track the items when the order of the array changes because then their index changes too and keys are not allowed to change
https://react.dev/learn/rendering-lists#rules-of-keys

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/settings/outputs.tsx
> +    setSettings: (GenericSettings: GenericSettings) => void
Something just doesn't sit right with me about how this entire structure is made. I can't put my finger on it, but that's mainly because I can't figure out what this entire component is trying to achieve. 
But I can say that the callback you get here is being sent down as a callback to the child components of this component and that's going to get confusing real fast.

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/settings/settingsButtons.tsx
> +    ].join(' ')
Just use simple string interpolation:
```
const classNames = `save-button ${operationMode === OperationMode.EDIT_VISIBILITY ? 'on' : ''}`
```
Comment applies for the other places where you are trying to do this trick as well.

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/settings/settingsButtons.tsx
> +        {!props.specificChannel ? (
Again, ternary is the wrong tool:
```
{!props.specificChannel && (
   // Your HTML
)}
```

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/settings/settingsButtons.tsx
> +    if (window.confirm('Changes have been made, are you sure you want to discard them?')) {
You can get rid of the nesting by doing something like this:
```
function handleDiscard(...) {
  if (hasChanges(settings) && !window.confirm(...)) {
    return
  }
  toggleSettingsPage()
}
```

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/settings/settingsInput.tsx
> +export default function SettingsInput(props: SettingsInputProps): JSX.Element {
Please don't make a "one does all" component. It only leads to complications and is a big violation of SRP. For example your `value` property is of type `string | boolean | number` which is basically the equivalent of using `any`.

Instead just have `TextInput`, `NumberInput` and `Checkbox` components. You allready know what type of input you have when you use `SettingsInput` because you need to specify `type` so you might as well use the correct input you want directly.

Do you yourself (and future maintence developers) a giant favour and delete this component.

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/settings/singleOutput.tsx
> +        : <></>
Again, ternary is the wrong tool for this

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/settings/singleOutput.tsx
> +                ) : (
Ternary is the wrong tool for this

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/tab/tab.tsx
> +  tabItem: TabData
Since the type is `TabData` the variable name should be `tabData` as well.

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/tab/tabContent.tsx
> +export default function TabContent(props: TabBarProps): JSX.Element {
I have mentioned this several times before: Don't name your components `xContent`.
"Content" is a concept. Any component can be the content of another component.
In this snippet:
```
<UserList>
  <User />
  <User />
  <User />
</UserList>
```
`User` is the content of `UserList`. We don't call `User` for `UserContent` becase then `User` should know about where it is beings used. And just like functions should be agnostic, so should components. 
There is nothing stopping from using `User` like this:
```
<div>
  <Header title="User Details" />
  <User />
</div>
```
Now `User` is not used as content, but if we have named the component `UserContent` we would have forced the component to only be used as "content".

This is the fourth time I am mentioning this to you. Come talk to me if it still doesn't make sense.

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/tab/tabs.tsx
> +      <TabContent tabData={tabData} selectedTab={selectedTab} />
To continue the don't name components `xContent`.
Here you are using a `xContent` component, but you aren't actaully parsing it as content which just further emphasizes that components shouldn't be named `xContent`

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/thumbnail/thumbnail.tsx
> +    // Redux hook:
Remove unnecessary comments.
Goes for the `// Render:` comment in this file as well

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/thumbnail/thumbnail.tsx
> +                <div className="boxComponent" key={index}>
Don't use `index` as `key`

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/thumbnail/thumbnailButton.tsx
> +  isTextView?: boolean
Is this necessary? Boolean flags are a bad practice/code smell

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/thumbnail/thumbnailButton.tsx
> +    ></button>
Close empty tag

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/thumbnail/thumbnailUsingImage.tsx
> +            ''
Ternary is the wrong tool

2023-03-21 11:13 UTC, LindvedKrvang commented on src/client/components/thumbnail/thumbnailUsingText.tsx
> +            ''
Ternary is the wrong tool

2023-03-21 11:13 UTC, LindvedKrvang commented on src/model/reducers/appNavReducer.ts
> +function defaultAppNavReducerState(): NavReducer {
Why "Reducer"?

2023-03-21 11:13 UTC, LindvedKrvang commented on src/model/reducers/mediaActions.ts
> +export function updateMediaFiles(
All the "update" functions in here does not update anything. They just wrap their input in a new object that also has a trype attribute...

2023-03-21 11:13 UTC, LindvedKrvang commented on src/model/reducers/mediaModels.ts
> +export interface HiddenFileInfo {
Why is there a need for a specific interface for hidden files? Why is isn't enough to just do `const hiddenFiles: Files[]`?

Also, currently ALL files are hidden files because `File` extends from `HiddenFileInfo`. This should be inverted.

2023-03-21 11:13 UTC, LindvedKrvang commented on src/model/reducers/settingsAction.ts
> +export function setTabData(amount: number): {
These names aren't that descriptive. The function is called `setTabData` and then takes a number and not any TabData. The number is just called `amount`, amount of what? Amount of TabData?

Looking at the implementation it looks like you are creating tabs (or in your case - tabData), so a more apt name would be `createTabData(amountOfTabsToCreate: number)`

Also in your implementation you could write:
```
createTabDate(amountOfTabsToCreate: number) {
 return Array(amountOfTabsToCreate).fill().map(index => {
    return {
      key: index + '',
      title: // Your code for setting title
    }
  })
}
```

2023-03-21 11:13 UTC, LindvedKrvang commented on src/model/reducers/settingsAction.ts
> +export function setScaling(
All the "set" methods in this file are not set methods but rather wrapper methods.

2023-03-21 11:13 UTC, LindvedKrvang commented on src/model/reducers/settingsModels.ts
> +export interface TabData {
Why is it called `TabData` and not just `Tab`?
Also, what is `key` being used for? It seems out of place.

2023-03-21 11:13 UTC, LindvedKrvang commented on src/model/reducers/settingsModels.ts
> +    outputs: OutputSettings[]
The type is `OutputSettings[]`, so the name should be `outputSettings`

2023-03-21 11:13 UTC, LindvedKrvang commented on src/model/schemas/settingsSchema.ts
> +// Following line says that all attributes are optional, then though the '.required' has been used.
The following line is out-commented, so it does nothing

2023-03-21 11:13 UTC, LindvedKrvang commented on src/model/services/mediaService.ts
> +    public secondsToTimeCode(
I will highly suggest to look into the library `date-fns`. It most likely has what is trying to be achieved here and then we don't have to deal with a ton of edgecases when it comes to dates/times

2023-03-21 11:13 UTC, LindvedKrvang commented on src/model/services/settingsFileService.ts
> +    isPreviousStructure(loadedFile: any): {
`isPrevious...` and `isNew...` is outdated allredy by time this PR is merged so I would suggest using other terms.
If a new structure is used would that then be `isNewNew...`?

Also, the names suggest that they do a simple yes and no check, but in the implementation you are doing the ACTUAL parsing...

2023-03-23 07:29 UTC, andr9528 commented on src/client/components/footer/operationModeEditVisibilityFooter.tsx
>  function resetOperationMode(): void {
That structure is also the one i aim for the files to have - just missed it in this one. Fixed now.

2023-03-23 07:32 UTC, andr9528 commented on src/client/components/header/header.tsx
> +                    ''
Done That now. I know i have a couple other places with similar code. I will try to do the same thing if i remember. If you do see any similar ones, that i have missed, do mention it :)

2023-03-23 07:33 UTC, andr9528 commented on src/client/components/header/header.tsx
> +            ) : null}
Done

2023-03-23 07:34 UTC, andr9528 commented on src/client/components/header/header.tsx
> +//CSS files:
Ya i know there are multiple files with such lines. Will be cleaning that up too. This one is gone now.

2023-03-23 07:38 UTC, andr9528 commented on src/client/components/header/headerButtons.tsx
> +function handleLoopStatus(activeTab: number): void {
I see what you mean. Will be going around - slowly - updating the event handler method names to better describe their operation.

2023-03-23 07:39 UTC, andr9528 commented on src/client/components/header/headerButtons.tsx
> +        ''
Done.

2023-03-23 07:46 UTC, andr9528 commented on src/client/components/header/time.tsx
> +        cleanTallyFile = mediaService.getCleanSelectedFile(settingsOutput)
Yes it looks simple, but during startup Cliptool actually seems to render 2-3 times, before it reaches a state where all the accessed objects and attributes no longer are undefined.

Ones i track down and possibly eliminate the extra re-renders on startup, then i would very much like to eliminate the try/catch. Why it does the extra renders at the moment, with undefined values at different places in the state, i do not know. If you have any suggestions as to why, do let me know.

2023-03-23 07:56 UTC, andr9528 commented on src/client/components/header/toggleButton.tsx
> +export default function ToggleButton(props: ToggleButtonProps): JSX.Element {
Not sure how/what needs to bwe changed, as what value that toggles the button on/off are different per button.

You are right that this could be moved to a shared folder, but as there are no other components, other than `<HeaderButtons>` that makes use of it, i don't see why. 
If some other non-header component where to use it, then yes it should be moved.

2023-03-23 08:04 UTC, andr9528 commented on src/client/components/settings/outputs.tsx
> +                            return <SingleOutput configChannel={item} index={index} output={props.settings.outputs[index]} key={index} setOutput={setOutput}/>
Fair Enough, but what would you suggest i use in this scenario?

2023-03-23 08:30 UTC, andr9528 commented on src/client/components/settings/outputs.tsx
> +    setSettings: (GenericSettings: GenericSettings) => void
We could have chat about the structure, if you want. But first let me try and explain the structure abit.

We have the `settings.tsx` which is the parent of this file, `settingsButtons.tsx` and `generalSettings.tsx`. 
`settingsButtons.tsx` and `generalSettings.tsx` are therefore siblings to this file.
`settingsButtons.tsx` needs to know of changes that `generalSettings.tsx` and the children of this file makes to the shared 'settings document', such that when requested it knows what to save.

This file has a child for each output in Cliptool, which houses a settings related to a single output, hence the name `singleOutput.tsx`.
Changes made by `singleOutput.tsx` on its output, needs to be saved to the shared 'settings document'.

2023-03-23 08:43 UTC, andr9528 commented on src/client/components/settings/settingsButtons.tsx
> +    if (window.confirm('Changes have been made, are you sure you want to discard them?')) {
Done that now.

2023-03-23 08:48 UTC, andr9528 commented on src/client/components/settings/settingsButtons.tsx
> +    ].join(' ')
Will do it - but not sure i am how big a fan of it for class names. 
If there were more than one optional class name, then using this setup, would make it more readable than using interpolation, in my mind.
Also this setup was suggested by Anders originally, so it can't be half bad right? :P

2023-03-23 08:50 UTC, andr9528 commented on src/client/components/tab/tab.tsx
> +  tabItem: TabData
Done

2023-03-23 08:52 UTC, andr9528 commented on src/client/components/settings/settingsButtons.tsx
> +        {!props.specificChannel ? (
Done

2023-03-23 08:55 UTC, andr9528 commented on src/client/components/thumbnail/thumbnailButton.tsx
> +    ></button>
Done

2023-03-23 08:59 UTC, andr9528 commented on src/client/components/thumbnail/thumbnailButton.tsx
> +  isTextView?: boolean
It is the lesser of 2 evils, when compared with the duplication that would be needed, afaik, to achieve what this flag does.

2023-03-23 09:00 UTC, andr9528 commented on src/client/components/thumbnail/thumbnailUsingImage.tsx
> +            ''
Gone.

2023-03-23 09:03 UTC, andr9528 commented on src/client/components/thumbnail/thumbnailUsingText.tsx
> +            ''
Gone

2023-03-23 09:17 UTC, andr9528 commented on src/client/components/settings/settingsInput.tsx
> +export default function SettingsInput(props: SettingsInputProps): JSX.Element {
I can see that pulling out a `Checkbox` component, makes some sense, although it does have some similar inputs as the others.
However `TextInput` and `NumberInput` would be 99% duplicates, as is evident from the cases in the switch, which i do not want.

Would like to have chat about the best way to split this - without introducing almost complete duplicated components.

2023-03-23 09:18 UTC, andr9528 commented on src/client/components/settings/singleOutput.tsx
> +                ) : (
Gone

2023-03-23 09:18 UTC, andr9528 commented on src/client/components/settings/singleOutput.tsx
> +        : <></>
Gone

2023-03-23 09:24 UTC, andr9528 commented on src/client/components/tab/tabContent.tsx
> +export default function TabContent(props: TabBarProps): JSX.Element {
It does somewhat make sense to me - however as i think i have also responded with before, i am unsure what name better match, or how it possibly should be restructured to better fit some completely new name scheme.
Would very much like a talk about it - when you have time for it.

2023-03-23 09:28 UTC, andr9528 commented on src/client/components/tab/tabs.tsx
> +      <TabContent tabData={tabData} selectedTab={selectedTab} />
As i wrote on your comment on that file, i would like a talk about the name.

The component is used to display the content of the selected tab. Don't currently know a better name. 
Might make more sense or help, when/if you see where on the UI it is placed.

2023-03-23 11:38 UTC, andr9528 commented on src/client/components/app.tsx
> +//CSS files:
Gone

2023-03-23 11:41 UTC, andr9528 commented on src/client/components/app.tsx
> +                        ? <Thumbnail/>
Merged to fewer lines. Also extracted the second ternary to a constant before the the return. Unsure if they is a good way to do it, but better than nestet ternary.

2023-03-23 12:00 UTC, andr9528 commented on src/model/reducers/settingsModels.ts
> +    outputs: OutputSettings[]
Fixed.

2023-03-23 13:10 UTC, andr9528 commented on src/model/schemas/settingsSchema.ts
> +// Following line says that all attributes are optional, then though the '.required' has been used.
Outcommented it temporarely as the code couldn't compile with it, for a different reason than its purpose.
Removing it for now, as i am unsure if it purpose is going to be needed in this repo.

2023-03-23 13:40 UTC, andr9528 commented on src/model/reducers/settingsAction.ts
> +export function setScaling(
I am not 100% sure, but i believe tt was a naming scheme that Kasper started using, as a replica of redux's documentation.

2023-03-23 13:49 UTC, andr9528 commented on src/client/components/thumbnail/thumbnail.tsx
> +    // Redux hook:
Gone

2023-03-23 13:51 UTC, andr9528 commented on src/client/components/thumbnail/thumbnail.tsx
> +                <div className="boxComponent" key={index}>
Okay, but what other thing would you suggest?
I understand why - just don't know of a better alternative, at the moment.

2023-03-27 08:43 UTC, LindvedKrvang commented on src/client/components/header/time.tsx
> +        cleanTallyFile = mediaService.getCleanSelectedFile(settingsOutput)
If this is to guard against udefined values, then why not just check for undefined?

2023-03-27 09:55 UTC, LindvedKrvang commented on src/client/components/settings/outputs.tsx
> +                            return <SingleOutput configChannel={item} index={index} output={props.settings.outputs[index]} key={index} setOutput={setOutput}/>
I don't know your domain, but ideal the entity you are looping over should have a id.
Else, chose something on unique on the entity.
What matters is that it is something unique and that the key is not changed when stuff move around inside the array

2023-03-27 09:58 UTC, LindvedKrvang commented on src/client/components/settings/outputs.tsx
> +    setSettings: (GenericSettings: GenericSettings) => void
I think we should have a talk :)

2023-03-27 10:01 UTC, LindvedKrvang commented on src/client/components/settings/settingsButtons.tsx
> +    ].join(' ')
> Also this setup was suggested by Anders originally, so it can't be half bad right? :P

We all make some bad calls sometimes (not necesarily saying this one is). That's why we review each others code and talk about potential implementations before implementing.

For the actual thing at hand here:
Why not apply the style directly in html? Why even extract it into a variable? `save-button` is always going to be applied to the button

2023-03-27 10:02 UTC, LindvedKrvang commented on src/client/components/settings/settingsInput.tsx
> +export default function SettingsInput(props: SettingsInputProps): JSX.Element {
Lets have a talk :)

2023-03-29 08:31 UTC, KvelaGorrrrnio reviewed
I have only review a part of it, but it becomes too cumbersome reviewing the rest, when the files are actively being changed and renamed.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on package.json
> +        "xml-js": "^1.6.11",
It does not look like this dependency is used anywhere. It will be a good idea to check which dependencies are actually needed.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/settings/settings.tsx
> +    const [settings, setSettings] = useState(_.cloneDeep(settingsService.getGenericSettings(reduxState.settings)))
Since there [should only be serializable data in the Redux store](https://redux.js.org/faq/organizing-state#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state), you could use something like the following, instead of using lodash.cloneDeep.
```typescript
function deepCloneState<T>(value: T): T {
  return JSON.parse(JSON.serialize(value))
}
```

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/model/reducers/indexReducer.ts
> +export type ReduxStateType = ReturnType<typeof indexReducer>
This should just be `State`. Which framework we use should be irrelevant. And `Type` is a filler word.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/app.tsx
> +const specificChannel = channel ? parseInt(channel) || 0 : 0
This is a good target to be extracted to its own class. By doing this we can encapsulate the interaction with browser specific logic.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/footer/operationModeEditVisibilityFooter.tsx
> +    appNavigationService.getActiveTab(reduxState.appNavigation),
`reduxState` can be renamed to `state`.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/app.tsx
> +    const isSettingsOpen = useSelector((storeUpdate: ReduxStateType) => storeUpdate.appNavigation.showSettingsActive)
`showSettingsActive` seems a bit oddly worded. `showSettings` or `isSettingsOpen` are better names for this.

Maybe consider if using binary flags for representing which component to show, is the correct way.
Another solution would be to user a router, and base it on the URL. Or have an enum with which page to show. Just food for thought.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/header/header.tsx
> +        (storeUpdate: ReduxStateType) => storeUpdate.appNavigation.connectionStatus)
`storeUpdate` should be renamed to state. There are conflicting use of store and state in the application.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/header/header.tsx
> +        (storeUpdate: ReduxStateType) => storeUpdate.appNavigation.connectionStatus)
`appNavigation` feels like the wrong name for what it contains.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/header/header.tsx
> +            {!connectionStatus && (
`connectionStatus` is not representative of what it contains. Either an enum like `ConnectionStatus` should be the value type or it should be renamed to `hasConnection`/`isConnected`.
It also makes sense to extract the JSX into a component. What this is doing should not be the responsibility of the header.
The usage of the component could be moved one layer up.
```typescript
{ !isConnected && <OfflineOverlay /> }
```

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/header/headerButtons.tsx
> +  const mixState: boolean = useSelector(
Most of the types here are not correct, since they might also be undefined. E.g. `mixState` should be `boolean | undefined`.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/header/headerButtons.tsx
> +export default function HeaderButtons(): JSX.Element {
Should this component only be able to hold buttons?
To have a more general description of what the component does, it could be named `HeaderActions`.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/header/headerButtons.tsx
> +      {reduxState.appNavigation.selectView === 0 && (
Instead of having multiple boolean flags for representing different view modes like selectView and textView; this could be modeled with an enum.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/header/headerButtons.tsx
> +  )
The socket connection should not be directly exposed to UI components.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/header/headerButtons.tsx
> +      !settingsService.getOutputSettings(reduxState.settings, activeTab).loopState
These `emitX` functions are doing more than just emitting an event. It also computes the inverse of the current state. So these functions are toggling the value and emitting that.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/header/time.tsx
> +    } catch {}
Why is this wrapped in a try-catch?

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/header/time.tsx
> +    const thumbnailUrl = mediaService.findThumbnail(cleanTallyFile, activeTab)
`find` and and `get` acts as synonyms. Since get is used most other places in the code, `findThumbnail` should be changed to `getThumbnail`.
And `Thumbnail` is a bit vague. Is it the thumbnail url, thumbnail image data or thumbnail object?
If it is base64 encoded image data, then hint towards that in the function name.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/model/services/mediaService.ts
> +    public secondsToTimeCode(
As we talked about yesterday, I don't think there is a need for adding a library for this since the use case is simple with very few edge cases. The logic for computing the time code should though not be a part of the media service, but on a service that is responsible for calculating/formatting timecodes.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/settings/general-settings.tsx
> +export default function GeneralSettings(props: GeneralSettingsProps): JSX.Element {
There is an inconsistency between the properties and the naming of the component. Since this is only concerned with CasparCG settings, perhaps it should be named as such – or the properties should not contain CasparCG abbreviations.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/settings/outputs.tsx
> +                ? <SingleOutput index={props.specificChannel - 1} outputSettings={props.outputSettings[props.specificChannel]} setOutputSettings={setOutput}/>
Why is it called `SingleOutput` and not `Output`?

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/settings/outputs.tsx
> +    specificChannel: number
There is some mismatch between the names channel and output – are they not the same?
But lets have a talk on that when we look at the domain model.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/settings/general-settings.tsx
> +}
`ccg` seems incorrect. We have a component called `GeneralSettings` where CasparCG named attributes are used.
Either this should be `CasparcgSettings` or `ccg` should be removed. Or some third option, where the matches.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/settings/general-settings.tsx
> +    function saveTempIpChange(event: React.ChangeEvent<HTMLInputElement>): void {
Is `Temp` necessary?

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/settings/general-settings.tsx
> +        props.onCcgSettingsChange(settings)
This might be a conscious decision, but data from two scopes are mixed here. The external settings are merged with an internal attribute, disregarding the other internal attributes.
An alternative could be to build the settings object from internal state and then pass that to `onSettingsChange`.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/settings/settings-buttons.tsx
> +export default function SettingsButtons(props: SettingsButtonsProps): JSX.Element {
`Buttons` describes how this was implemented not what its purpose is. An option could be to rename it to `SettingsActions`.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/settings/settings-buttons.tsx
> +  return hasChanged
You can return the expression directly without binding it.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/settings/settings-buttons.tsx
> +  toggleSettingsPage()
It would be nice if we closed the settings page instead of toggling. If, by chance, this is called twice, you get unexpected behaviour.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/settings/settings.tsx
> +const specificChannel = channel ? parseInt(channel) || 0 : 0
Similar code is being used in other places. Instead of using 0 as the empty value, which leads to the specificChannel to be off by one, until we actually use the value somewhere.
I have already mentioned in a previous comment that it will be a good idea to put this into its own class.

If `0` is used to avoid untyped `undefined` values, then  I will suggest using the `Maybe` type:
```typescript
type Maybe<T> = NonNullable<T> | undefined
```

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/settings/settings.tsx
> +    }
What is the purpose of this function?

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/settings/settings.tsx
> +        setSettings(settingsCopy)
This can be reduced to:
```suggestion
        setSettings({ ...settings, ccgSettings })
```

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/settings/single-output.tsx
> +  configChannel?: CcgConfigChannel
Why is this optional?

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/settings/single-output.tsx
> +                    : reduxState.settings.ccgConfig.channels[props.index].videoMode}
If you changed the property from configChannel to videoMode, then you could get rid of the ternary and the dependency on reduxState.
If `configChannel` and `channels[index]`, that is also a viable way to go about it.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/settings/single-output.tsx
> +                        {reduxState.media.folderList.map(
If the `folderList`, which could be renamed to `folders`, was passed as a property, then you could get rid of the reduxState dependency.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/thumbnail/thumbnailButton.tsx
> +  isTextView?: boolean
As I mention in a previous comment, using an enum for view modes would be a good way to go :)

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/thumbnail/thumbnailPicture.tsx
> +  const classNames: string = `thumbnailImage ${settingsService.isThumbnailSelected(file.name, reduxState.settings, activeTab) ? 'selected-thumb' : ''}`
For readability, I would suggest creating a list of potential classNames and join them, like so:
```suggestion
  const classNames = [
    'thumbnailImage',
     settingsService.isThumbnailSelected(file.name, reduxState.settings, activeTab) ? 'selected-thumb' : '',
   ].join(' ')
```

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/thumbnail/thumbnailPicture.tsx
> +        .mediaFiles.find((predicate: MediaFile) => predicate.name === props.file.name)
What is the difference between the `props.file` and `predicate`? Don't they contain the same data?

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/thumbnail/thumbnailUsingImage.tsx
> +    (storeUpdate: ReduxStateType) => appNavigationService.getActiveTab(storeUpdate.appNavigation))
There are multiple places where the ending parenthesis is in a nested scope. For readability it would be nice if it was move down a line. But I guess that running a linter on it will do the trick.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/thumbnail/thumbnailUsingImage.tsx
> +                .slice(-45)}
What is happening here?

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/thumbnail/thumbnailUsingImage.tsx
> +export default function ThumbnailUsingImage(props: ThumbnailUsingImageProps): JSX.Element {
In the code, graphical data is referred to as a picture and image. We should stick with one. I would prefer Image. And then this could be `ImageThumbnail` and for text view `TextThumbnail`.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/thumbnail/timeCode.tsx
> +  const time: [number, number] = useSelector(
This should not be named time. It is a time range.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/thumbnail/timeCode.tsx
> +}
I am not a fan of the amount of useSelectors we use to get the same data over and over again. This is a component that should just be concerned with displaying a timecode. But it also have to know how our state store is structured, what active tab we are on. All of that should be removed from this component. If we pass the duration and frameRate as props, this component can be simplified to:
```typescript
interface TimeCodeProps {
  duration: number
  frameRate: number
}

export default function TimeCode(props: TimeCodeProps): JSX.Element {
  return (
    <div className='time-code'}>
        { mediaService.secondsToTimeCode(time, frameRate) }
    </div>
  )
}
```
I know that currently it is handling the text view version as well, but creating a variation of this for the text view should not be a difficult thing to do.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/shared/button.tsx
> +  isHidden?: boolean
What is the purpose of this attribute? If you have a view were the button should not be displayed, then use conditional rendering.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/tab/tabContent.tsx
> +function onValidSwipe(direction: SwipeDirection, props: TabContentProps) {
Food for thought: All the component props are passed in, but you only need `selectedTab` and the length of `tabData`. By restricting the function parameters to these, you get a function that has a higher potential for reusability.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/thumbnail/text-thumbnail.tsx
> +  const classNames: string = `thumbnail-text-view ${isSelected ? 'selected-thumb' : ''}`
The css class should be consistent with the component naming: `text-thumbnail`

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/thumbnail/text-thumbnail.tsx
> +  const isSelected: boolean = settingsService.isThumbnailSelected(props.file.name, reduxState.settings, activeTab)
By making this a prop, you can remove the reduxState dependency.

2023-03-29 08:31 UTC, KvelaGorrrrnio commented on src/client/components/thumbnail/thumbnail-button.tsx
> +  buttonClassName: string
Why not just call it `className`?

2023-03-29 08:32 UTC, KvelaGorrrrnio reviewed
I have only reviewed a part of it, but it becomes too cumbersome reviewing the rest, when the files are actively being changed and renamed.

2023-03-29 09:41 UTC, andr9528 commented on src/client/components/tab/tabContent.tsx
> +function onValidSwipe(direction: SwipeDirection, props: TabContentProps) {
Done as suggested.

2023-03-29 13:08 UTC, andr9528 commented on package.json
> +        "xml-js": "^1.6.11",
Have removed a handful of dependencies. Code builds and runs just fine between removing each one and efter all removals.
Unsure if 'serialport' / 'socket.io' / 'socket.io-client' can be removed or not.
Other than those three, i think the dependencies have been cleaned quite nicely.
Might also be some under devDependencies, but haven't looked at those.

2023-03-29 13:19 UTC, andr9528 commented on src/client/components/settings/settingsInput.tsx
> +export default function SettingsInput(props: SettingsInputProps): JSX.Element {
After our chat, the file has been split into multiple components with some slight duplication, on a level that i deem acceptable.

2023-03-29 13:21 UTC, andr9528 commented on src/client/components/tab/tabContent.tsx
> +export default function TabContent(props: TabBarProps): JSX.Element {
Have reworked the tabs sytem yet again - thus removing the tagContent.

Currently it looks correct, but unsure if i mangaged to copy back in the existing CSS.

2023-03-29 13:23 UTC, andr9528 commented on src/client/components/tab/tabs.tsx
> +      <TabContent tabData={tabData} selectedTab={selectedTab} />
Tabs has been reworked majorly again, since your last view of them.

2023-03-29 13:32 UTC, andr9528 commented on src/client/components/thumbnail/thumbnailButton.tsx
> +  isTextView?: boolean
Fixed by changing the input to take the css class instead.
Havn't seen your exact comment yet, Anders, at the time of writing this, but might still make sense to apply that change anyway for benefits other places.

2023-03-30 07:08 UTC, andr9528 commented on src/client/components/header/header.tsx
> +            {!connectionStatus && (
Attribute has been renamed as suggested, and JSX extracted to its own component, and displayed center mass, when `!isConnect`, from app.tsx.

2023-03-30 09:32 UTC, andr9528 commented on src/client/components/app.tsx
> +const specificChannel = channel ? parseInt(channel) || 0 : 0
Has been encapsulated in 'BrowserService'.

2023-03-30 10:21 UTC, andr9528 commented on src/client/components/app.tsx
> +    const isSettingsOpen = useSelector((storeUpdate: ReduxStateType) => storeUpdate.appNavigation.showSettingsActive)
Has been updated to `isSettingsOpen`.

2023-03-30 10:25 UTC, andr9528 commented on src/client/components/header/header.tsx
> +        (storeUpdate: ReduxStateType) => storeUpdate.appNavigation.connectionStatus)
Have renamed `storeUpdate` everywhere to `state`.

2023-03-30 10:29 UTC, andr9528 commented on src/client/components/header/header.tsx
> +        (storeUpdate: ReduxStateType) => storeUpdate.appNavigation.connectionStatus)
Well, it contains values that all effect what is being shown.
If any of them is changed, some form of re-rendering to some view is done, which fits with the name navigation.

2023-03-30 10:33 UTC, andr9528 commented on src/client/components/header/time.tsx
> +    const thumbnailUrl = mediaService.findThumbnail(cleanTallyFile, activeTab)
Renamed to `getBase64ThumbnailUrl()`.

2023-03-30 10:43 UTC, andr9528 commented on src/client/components/header/time.tsx
> +    } catch {}
There are some occasional errors during the call if performed while Cliptool is starting, that i have simply not been able to figure out why. 
As Cliptool re-renders this components a few times at startup, i have just been allowing the re-renders to correct it.

Have removed it for now, but will need a hand figuring out the error, and how to fix it.

2023-03-30 10:53 UTC, andr9528 commented on src/client/components/header/toggleButton.tsx
> +export default function ToggleButton(props: ToggleButtonProps): JSX.Element {
Has been converted into button.tsx under shared, making use of giving css class to indicate if it is on/off.

2023-03-30 10:55 UTC, andr9528 commented on src/client/components/settings/outputs.tsx
> +    setSettings: (GenericSettings: GenericSettings) => void
Let me know if the changes that has been made, together with out chat, has helped, or maybe we should discuss it further.

2023-03-30 10:57 UTC, andr9528 commented on src/client/components/settings/settingsButtons.tsx
> +    ].join(' ')
Have reworked it to be applied via string interpolation, as suggested. `save-button` is being kept in a constant, to reduce duplication slightly.

2023-03-30 11:00 UTC, andr9528 commented on src/model/reducers/appNavReducer.ts
> +function defaultAppNavReducerState(): NavReducer {
To make use of the suggested naming scheme from redux. 
Could maybe make another name, but following the suggested naming scheme from them, fell right to do.

2023-03-30 11:05 UTC, andr9528 commented on src/model/reducers/mediaActions.ts
> +export function updateMediaFiles(
The naming scheme `updateX` / `setX` etc. comes from Redux's documentaion. 
That doesn't mean it is perfect - but it can't be half bad, if a major package like Redux makes use of it.

2023-03-30 11:11 UTC, andr9528 commented on src/model/reducers/mediaModels.ts
> +export interface HiddenFileInfo {
`File` contans more, uneccecarry, information than is needed to determin if a file has changed.
As the `hiddenFiles` are written to a Json file, it is propably wise to keep it as small as possible, for faster save/load time, and to not bloat the system, incase there are 100s of files being hidden.

2023-03-30 11:14 UTC, andr9528 commented on src/model/reducers/settingsAction.ts
> +export function setTabData(amount: number): {
Have extracted the code to create the tab data to a new function, as you suggested.

I am however working out in my mind, if `TabData`, is even needed, or if there are some other more appropriate array to iterate over, when creating tabs. 
In the end `TabData`, is likely going to die - just going to be a moment, while i work i out.

2023-03-30 11:17 UTC, andr9528 commented on src/model/reducers/settingsModels.ts
> +export interface TabData {
As i commented on one of your other ocmments, i am working out how to eradicate TabData.

For what it contains, it is data relevant to creating tabs, i.e title of the tabs and position, in form of a key/index.

2023-03-30 11:23 UTC, andr9528 commented on src/model/services/mediaService.ts
> +    public secondsToTimeCode(
`secondsToTimeCode()` has been moved to new `TimeService`.

2023-03-30 11:28 UTC, andr9528 commented on src/model/services/settingsFileService.ts
> +    isPreviousStructure(loadedFile: any): {
When naming them i was considering `isStructureBefore2_1_5` and `isStructureAfter2_1_5`, but i am not a fan of the underscores/numbers in a method name like that.

I am open for suggestions :)

2023-03-30 11:48 UTC, andr9528 commented on src/client/components/settings/settings.tsx
> +        setSettings(settingsCopy)
Applied.

2023-03-30 11:51 UTC, andr9528 commented on src/client/components/settings/settings.tsx
> +    }
Fairly certain i was just missing a call to setSettings(...). Not sure how i missed that. Fixed now.

2023-03-30 12:00 UTC, andr9528 commented on src/client/components/settings/settings.tsx
> +    const [settings, setSettings] = useState(_.cloneDeep(settingsService.getGenericSettings(reduxState.settings)))
I take that you meant `JSON.stringify(...)`. Have applied that change. 
Function to do the deep cloning is in this file - for now - but should most likely be moved somewhere else, just not sure where.

2023-03-30 12:07 UTC, andr9528 commented on src/model/reducers/indexReducer.ts
> +export type ReduxStateType = ReturnType<typeof indexReducer>
Done

2023-03-30 12:09 UTC, andr9528 commented on src/client/components/footer/operationModeEditVisibilityFooter.tsx
> +    appNavigationService.getActiveTab(reduxState.appNavigation),
Done

2023-03-30 12:20 UTC, andr9528 commented on src/client/components/header/headerButtons.tsx
> +  const mixState: boolean = useSelector(
Code appears to work just fine after removing `?` from each line - no errors/warnings in console, yet.

2023-03-30 12:23 UTC, andr9528 commented on src/client/components/header/headerButtons.tsx
> +export default function HeaderButtons(): JSX.Element {
Is now names `ControlActions`. 
Might also make sense to move out of 'header' folder, but as header is only one to use it, i think it is fine to keep it here, for now.

2023-03-30 12:23 UTC, andr9528 commented on src/client/components/header/headerButtons.tsx
> +      {reduxState.appNavigation.selectView === 0 && (
Has been modeled as an enum inside `BrowserService`.

2023-03-30 13:18 UTC, andr9528 commented on src/client/components/thumbnail/thumbnail-button.tsx
> +  buttonClassName: string
Done that now.

2023-03-31 06:43 UTC, andr9528 commented on src/client/components/thumbnail/text-thumbnail.tsx
> +  const isSelected: boolean = settingsService.isThumbnailSelected(props.file.name, reduxState.settings, activeTab)
Done

2023-03-31 06:47 UTC, andr9528 commented on src/client/components/shared/button.tsx
> +  isHidden?: boolean
I had implemented it as it was before. Have removed that attribute and used conditional rendering now.

2023-03-31 06:53 UTC, andr9528 commented on src/client/components/settings/outputs.tsx
> +                ? <SingleOutput index={props.specificChannel - 1} outputSettings={props.outputSettings[props.specificChannel]} setOutputSettings={setOutput}/>
Have renamed it to `Output`. Was mainly done to easier differentiate between the single and multiple outputs tsx file, as their names only differentiate by the single 's' at the end of the file with multiple in.

2023-03-31 06:58 UTC, andr9528 commented on src/client/components/settings/general-settings.tsx
> +    function saveTempIpChange(event: React.ChangeEvent<HTMLInputElement>): void {
Well, without it the method name could/would indicate that changes where saved, and i'd very easily assume persistet, which isn't the case. The method saves changes made to the temporary copy used to keep track of changes until either save or discard is done. By including 'temp' i hoped that it would better indicate that the changes aren't permanent - yet.

2023-03-31 07:06 UTC, andr9528 commented on src/client/components/settings/general-settings.tsx
> +        props.onCcgSettingsChange(settings)
Its a conscious decision. The internal attribute are used to mirror and track changes to atributes, that should on change be mirror back to the original source. The original source is being kept up to date, such that when the user clicks save, the `SettingsActions` know of any changes that has been done, and can directly save it.

2023-03-31 07:06 UTC, andr9528 commented on src/client/components/settings/settings-buttons.tsx
> +export default function SettingsButtons(props: SettingsButtonsProps): JSX.Element {
Has been renamed to `SettingsActions`.

2023-03-31 07:08 UTC, andr9528 commented on src/client/components/settings/settings-buttons.tsx
> +  return hasChanged
Was orinally doing that, but when i was debuging something i was printing hasChanged. 
Forgot to change it back - fixed now.

2023-03-31 07:09 UTC, andr9528 commented on src/client/components/settings/settings.tsx
> +const specificChannel = channel ? parseInt(channel) || 0 : 0
Has been centralized in `BrowserService`.

2023-03-31 08:11 UTC, andr9528 commented on src/client/components/settings/single-output.tsx
> +  configChannel?: CcgConfigChannel
Have removed the ability for it to be optional, by pulling the call done in case of it being optional up a level.

2023-03-31 08:13 UTC, andr9528 commented on src/client/components/settings/single-output.tsx
> +                    : reduxState.settings.ccgConfig.channels[props.index].videoMode}
Has been fixed by not allowing optional `configChannel`.

2023-03-31 08:19 UTC, andr9528 commented on src/client/components/settings/single-output.tsx
> +                        {reduxState.media.folderList.map(
Has been renamed to `folders` and pulled to being a prop input.

2023-03-31 08:28 UTC, andr9528 commented on src/client/components/thumbnail/thumbnailPicture.tsx
> +  const classNames: string = `thumbnailImage ${settingsService.isThumbnailSelected(file.name, reduxState.settings, activeTab) ? 'selected-thumb' : ''}`
Improved readabily by pulling the boolean condition to the line above. 
Lindved is not a fan of your suggested way, and much rather have use use string interpolation, which i think is a good way to do it, when there is only one optional. If there are multiple optional class names, then i will make use of the suggested way.

2023-03-31 08:53 UTC, andr9528 commented on src/client/components/thumbnail/thumbnailPicture.tsx
> +        .mediaFiles.find((predicate: MediaFile) => predicate.name === props.file.name)
I think i originally added it mainly for the use of `useSelector`, such that the component would update, should the file change.

Have removed that `useSelector`, and cut back the input to just the 'fileName', as that is all being used in here from the file. Did something similar to 'ThumbnailButton' at the same time.

2023-03-31 08:57 UTC, andr9528 commented on src/client/components/thumbnail/thumbnailUsingImage.tsx
> +    (storeUpdate: ReduxStateType) => appNavigationService.getActiveTab(storeUpdate.appNavigation))
Fixed.

There are ALOT of things that i'd love to run a linter to fix. Don't know how easy it is to spot on GitHub, but many files have different indentation, to a point where my VS Code some times have a hard time figuring out how the indentation should be for a new line, as it is constantly trying to update the used style for the project.

2023-03-31 08:58 UTC, andr9528 commented on src/client/components/thumbnail/thumbnailUsingImage.tsx
> +                .slice(-45)}
Not entirely sure. It is part of the original code that Kasper made, so i'd/we'd need to ask him.

2023-03-31 09:06 UTC, andr9528 commented on src/client/components/thumbnail/thumbnailUsingImage.tsx
> +export default function ThumbnailUsingImage(props: ThumbnailUsingImageProps): JSX.Element {
First of, `ThumbnailUsingImage` has been renamed to `ImageThumbnail`, and `ThumbnailUsingText` has been renamed to `TextThumbnail`.

If you saw two components called `ImageThumbnail` and `ThumbnailImage` what would you expect they do?
By calling the component used by `ImageThumbnail` `ThumbnailPicture`, it differentiats more clearly that they are different, rather than just ordering of words.

2023-03-31 09:10 UTC, andr9528 commented on src/client/components/thumbnail/timeCode.tsx
> +  const time: [number, number] = useSelector(
Is it a range thought? When:
- The first number is total duration.
- The second numbers is elapsed duration.

I am not sure i'd call that a range, but also not sure what other name could be applied to better describe it.
I am open for ideas.

2023-03-31 09:49 UTC, andr9528 commented on src/client/components/thumbnail/timeCode.tsx
> +}
Have made some improvements to it:
- Removed 'activeTab' useSelector.
- Changed 'isTextView' flag to 'classNames' string input, such that from outside extra class names can be applied.
- Removed call to `isThumbnailSelected()`, as conditional rendering is already applied outside, and thus always return true.
- Removed 'file' from props, as it is unused now.

The `useSelector()` for time and framerate remains, as we want the smallest possibly component to re-render when needed. If it was to be passed in from the parent, the parent would need to listen to it and thus re-render a much larger component.
Also we aren't talking about 1-2 re-renders every so often. it is constantly re-rendering approx. as many times per seconds as the framerate.
If you were to log the `time`, you would see that changes happen to it constantly, even if it simply says `[0, 0]`.

Now that i think about, maybe a check could be added to only dispatch the time change in redux, if it differentiates from what already is there.

2023-04-17 08:38 UTC, andr9528 commented on src/client/components/header/headerButtons.tsx
> +  )
Has been moved to new socketService, encapsulating all 'socket.emit's.

2023-04-17 08:40 UTC, andr9528 commented on src/client/components/header/headerButtons.tsx
> +      !settingsService.getOutputSettings(reduxState.settings, activeTab).loopState
With the move over to socketService, the responsibility of toggling the value has been kept in the file, while the emit has moved to socketService.

2023-04-17 08:41 UTC, andr9528 commented on src/client/components/header/time.tsx
> +    } catch {}
Issue has been solved.

2023-04-17 08:42 UTC, andr9528 commented on src/client/components/settings/general-settings.tsx
> +export default function GeneralSettings(props: GeneralSettingsProps): JSX.Element {
has been renamed to 'CasparcgSettingsForm'.

2023-04-17 08:47 UTC, andr9528 commented on src/client/components/settings/outputs.tsx
> +    specificChannel: number
We had a talk about it, and from my understanding decided that would be addressed when splitting the frontend and backend.

It makes sense for the backend to call it a channel, as it is closer to CasparCG, where that terminology comes from. On the other hand, seeing it from a users perspective, it is sent to an output of some sort, so the name Output makes sense from the clients side.

2023-04-17 08:48 UTC, andr9528 commented on src/client/components/settings/general-settings.tsx
> +}
With the renamed component name, this has also been solved.

2023-04-17 08:50 UTC, andr9528 commented on src/client/components/settings/settings-buttons.tsx
> +  toggleSettingsPage()
Not sure if this has been sufficently solved, with the changes since review. Let me know if more changes related to this is needed.

2023-04-17 08:56 UTC, andr9528 commented on src/client/components/thumbnail/text-thumbnail.tsx
> +  const classNames: string = `thumbnail-text-view ${isSelected ? 'selected-thumb' : ''}`
Applied the suggested name change, and something similar for the image-thumbnail component.

2023-04-18 05:38 UTC, KvelaGorrrrnio commented on src/client/services/jsx-service.ts
What problem does this service solve, that a ternary does not?

2023-04-18 05:42 UTC, KvelaGorrrrnio commented on src/client/components/app/app.tsx
> +    const isConnected: boolean = useSelector(
There is a inconsistency in explicit and not explicit type definitions here.
Personally I don't see the need for it in this case, but as long as it is consistent, I'm content.

2023-04-18 05:47 UTC, KvelaGorrrrnio commented on src/client/components/app/app.tsx
> +    }
I will suggest changing the behaviour of `browserService.getChannel` from providing the unsanitized value from the URL, to sanitizing it including shifting it to being 0-indexed.
The browser is not a part of the business logic for the application, and the browserService should shelter us from the complexity of handling that kind of input.

2023-04-18 05:49 UTC, KvelaGorrrrnio commented on src/client/components/app/app.tsx
> +                            <Main />))
Should settings not be allowed to be displayed unless there is an active connection?
If that is the case, then how would you go about setting the connection information?

2023-04-18 06:09 UTC, KvelaGorrrrnio commented on src/client/components/app/app.tsx
> +                            <Main />))
The conditional rendering would be better handled by a if-statement sequence or switch-case if you can combine the variables into a state indicator.
```typescript
if (!isConnected) {
  return (<OfflineOverlay />)
}
if (isSettingsOpen) {
  return (<Settings />)
}

return (<Main />)

// or

switch (stateIndicator) {
  case ApplicationState.OFFLINE:
    return (<OfflineOverlay />)
  case ApplicationState.SETTINGS:
    return (<Settings />)
  default:
    return (<Main />)
}
```

Note that the enum values should have better names :)

2023-04-18 06:25 UTC, KvelaGorrrrnio commented on src/client/components/footer/operation-mode-edit-visibility-footer/operation-mode-edit-visibility-footer.scss
> +}
This can me simplified by using the & operator of scss. It will also more clearly indicate the relation between the classes.

```suggestion
.operation-mode-edit-visibility-footer {
  display: flex;
  justify-content: center;
  align-items: center;

  &__text {
    color: #4175e6;
    font-size: 35px;
    text-align: center;
  }
  
  &__controls button {
    margin-left: 10px;
    background-color: #808080;
    top: 25%;
  }
}
```

2023-04-18 12:28 UTC, KvelaGorrrrnio commented on src/client/components/footer/operation-mode-edit-visibility-footer/operation-mode-edit-visibility-footer.tsx
>  const DESCRIPTION_TEXT = 'You are currently editing the visibility of files.'.toUpperCase()
Since these are static texts, with variable names that does not describe the contents, it would be preferable to have them directly in the JSX.

2023-04-18 12:43 UTC, KvelaGorrrrnio commented on src/client/components/footer/operation-mode-footer.tsx
> +    settingsService.getOutputSettings(state.settings, activeTab)?.operationMode)
The type is incorrect, it can also be undefined.

2023-04-18 12:53 UTC, KvelaGorrrrnio commented on src/client/components/header/control-buttons/control-actions.tsx
> +            >LOOP</Button>
This is a clickable element, but button is labeling this incorrectly.
The correct term for this is a switch. I would recommend creating `Switch` component such that this becomes:
```suggestion
            <Switch
              onChange={(isChecked: boolean) => setLoopState(activeTab, !isChecked)}
              checked={outputSettings.loopState}
            >LOOP</Switch>
```

2023-04-18 12:57 UTC, KvelaGorrrrnio commented on src/client/components/header/control-buttons/control-actions.scss
> +.control-button {
The class is not consistent with the filename, and the folder where this is placed is should be called control-actions.

2023-04-18 13:03 UTC, KvelaGorrrrnio commented on src/client/components/header/control-group/control-group.scss
> +.control-background {
There is an inconsistency between filename an class name.

2023-04-18 13:43 UTC, KvelaGorrrrnio commented on src/client/components/header/control-buttons/control-actions.tsx
> +  const buttonBaseCss = "control-button"
If this css class is necessary, then it should be changed to something like `control-action`.

2023-04-18 13:44 UTC, KvelaGorrrrnio commented on src/client/components/header/control-buttons/control-actions.tsx
> +          <ControlGroup>
After further thought, `ActionGroup` might describe the component better.

2023-04-21 07:32 UTC, KvelaGorrrrnio commented on src/client/components/header/timer/timer.tsx
> +                    mediaOutput?.time,
Two things:
1. `TimeService.secondsToTimeCode` expects the first argument to of type `[number, number]`, but here we might be parsing in an undefined value. To make it more explicit, the function should not tolerate undefined, and then you should give the function a valid input – either by defining a fallback value or using a conditional.
2. The method is called `secondsToTimeCode` but you are not providing seconds as input. You are providing a tuple of timestamps.

2023-04-21 07:42 UTC, KvelaGorrrrnio commented on src/client/components/header/timer/timer.tsx
> +                    playingFileType ?? 'UNKNOWN'
You have a `FileType` enum. It makes sense to use that as the type for this argument.

2023-04-24 07:08 UTC, andr9528 commented on src/client/components/header/timer/timer.tsx
> +                    playingFileType ?? 'UNKNOWN'
Would very much like to use the enum as the argument type, however the value originally comes from CasparCG, so it has to be cast at some point.
I just now tried to cast it to `FileType`, but was unable to do so, following a handfull of different online guides.

2023-04-24 07:42 UTC, andr9528 commented on src/client/components/header/timer/timer.tsx
> +                    mediaOutput?.time,
1. Added a ternary that checks if `mediaOutput` exist. If not, it simply gives a `[0, 0]` tuple.
2. The input that is given is a tuple of `Elapsed Duration` & `Total Duration`. Have renamed function and first argument to reflect this.

2023-04-24 07:49 UTC, andr9528 commented on src/client/components/header/control-buttons/control-actions.tsx
> +          <ControlGroup>
Has been renamed.

2023-04-24 08:04 UTC, andr9528 commented on src/client/components/header/control-buttons/control-actions.tsx
> +  const buttonBaseCss = "control-button"
From what i can gather, it is necessary. I have however reduced duplicate css between this and the start button when in manual mode.

2023-04-24 08:23 UTC, andr9528 commented on src/client/components/header/control-group/control-group.scss
> +.control-background {
Has been renamed to better fit new `action-group` name.

2023-04-24 08:29 UTC, andr9528 commented on src/client/components/header/control-buttons/control-actions.scss
> +.control-button {
Filename and Folder name has been updated. Not sure if a css class name is allowed to be plural, so it have kept it singular, for the moment. Let me know if plural is ok.

2023-04-24 09:38 UTC, andr9528 commented on src/client/components/header/control-buttons/control-actions.tsx
> +            >LOOP</Button>
Have applied your suggestion to all 5 buttons that functions as switches.

2023-04-24 09:39 UTC, andr9528 commented on src/client/components/footer/operation-mode-footer.tsx
> +    settingsService.getOutputSettings(state.settings, activeTab)?.operationMode)
Fixed.

2023-04-24 09:54 UTC, andr9528 commented on src/client/components/footer/operation-mode-edit-visibility-footer/operation-mode-edit-visibility-footer.scss
> +}
Suggestion has been applied.

2023-04-24 09:55 UTC, andr9528 commented on src/client/components/footer/operation-mode-edit-visibility-footer/operation-mode-edit-visibility-footer.tsx
>  const DESCRIPTION_TEXT = 'You are currently editing the visibility of files.'.toUpperCase()
Has been moved out of the constants.

2023-04-24 10:14 UTC, andr9528 commented on src/client/components/app/app.tsx
> +                            <Main />))
Moved logic to new component making use of if statements to form shortcuts throught the component.

2023-04-24 10:25 UTC, andr9528 commented on src/client/components/app/app.tsx
> +    }
Has been updated to shift over the number to be 0-indexed.

2023-04-24 10:26 UTC, andr9528 commented on src/client/components/app/app.tsx
> +    const isConnected: boolean = useSelector(
Added missing type to `isSettingsOpen`.

2023-04-24 10:27 UTC, andr9528 commented on src/client/services/jsx-service.ts
Service is gone now, replaced by `ComponentDecider`. 
Note entirely happy with its name, but not sure how to better name it.

2023-05-16 08:32 UTC, LindvedKrvang commented on src/client/components/component-decider.tsx
> +export default function ComponentDecider() {
`ComponentDecider` is a quite broad name and it needs some context. Is it trying to decide a component for the Header? For the Footer? For an input field? `ComponentDecider` leads one to believe that it can be used over and over again, but that is not the purpose of this component.

It looks this wants to render the body of you application. Just like you have a `Header` component, then calling this `Body` will also be fine.

2023-05-16 08:32 UTC, LindvedKrvang commented on src/client/components/header/action-group/action-group.tsx
> +  <div className={`c-action-group ${props.classNames ?? ''}`.trimEnd()}>
Why do you need to `.trimEnd()`?

2023-05-16 08:32 UTC, LindvedKrvang commented on src/client/components/header/control-actions/control-actions.scss
> +  font-size: 0.9em;
Please don't mix units. Either stick to `em` or `px` through your entire project. I vote for `em`

2023-05-16 08:32 UTC, LindvedKrvang commented on src/client/components/header/control-actions/control-actions.tsx
> +            >LOOP</Switch>
Please format tags that has content like so:
```
<Switch ...>
    LOOP
</Switch>
```
This gives a clear overview of when tags starts and ends and what their content is.

2023-05-16 08:32 UTC, LindvedKrvang commented on src/client/components/header/timer/timer.tsx
> +                {timeService.durationToTimeCode(
Be very aware of the methods you call from the `render` method. These methods is going to be executed over and over, potentially multiple times a second. Therefore these methods should not be doing math or any other operations that might take time.

2023-05-16 08:32 UTC, LindvedKrvang commented on src/client/components/main.tsx
> +// TODO: possibly find a better name
Yes

2023-05-16 08:32 UTC, LindvedKrvang commented on src/client/components/offline-overlay/offline-overlay.tsx
> +export default function OfflineOverlay(): JSX.Element {
Does this really need its own component?

2023-05-16 08:32 UTC, LindvedKrvang commented on src/client/components/shared/labelled-text-input/labelled-text-input.tsx
> +export default function LabelledTextInput(props: LabelledTextInputProps): JSX.Element {
Just call it `TextInput` and give it an optional value for the label.
Then in your render method you do:
```
return (
  <>
    {props.label ?? (
      <label className={...}>props.label</label>
    )
    <input type="text" ... />
  </>
)
```
Your `Label` component is overkill.
And instead of the `<br>` you are using in your `Label` component, you should just use CSS.

2023-05-16 08:32 UTC, LindvedKrvang commented on src/client/components/settings/casparcg-settings-form/casparcg-settings-form.tsx
> +            <hr />
Is this necessary?

2023-05-16 08:32 UTC, LindvedKrvang commented on src/client/components/settings/output/output.tsx
> +    const [label, setLabel] = useState(props.outputSettings.label)
Why not just do: `const [outputSettings, setOutputSettings] = useState(props.outputSettings)`?

2023-05-16 08:32 UTC, LindvedKrvang commented on src/client/components/settings/output/output.scss
> +  color: rgb(255, 255, 255);
Don't use rgb, just use the color: `color: white`

2023-05-16 08:32 UTC, LindvedKrvang commented on src/client/components/settings/output/output.tsx
> +    const fieldCss: string = 'settings-input-field'
`settings-input-field` is a CSS selector

2023-05-16 08:32 UTC, LindvedKrvang commented on src/client/components/settings/output/output.tsx
> +    const tickCss: string = 'settings-tick-field'
Do you mean `checkbox`?

2023-05-16 08:32 UTC, LindvedKrvang commented on src/client/components/shared/button.tsx
> +    <div onClick={props.onClick} className={props.classNames}>
Why not use an actual button?

2023-05-16 08:32 UTC, LindvedKrvang commented on src/client/components/shared/swipeable.tsx
> +  const [touchStart, setTouchStart] = useState<Point | null>(null)
Just write:
`const [touchStart, setTourchStart] = useState<Point>()`
this makes the type `Point | undefined` which is nicer to work with in Typescript.

Also, everytime you have to parse undefined or null to something you should take a deep inhale (preferably through your nose) so you can smell the odor of the giant code smell. And if that is not enough you should look behind you to see the giant red flag ;)

2023-05-16 08:32 UTC, LindvedKrvang commented on src/client/components/shared/swipeable.tsx
> +  disallowSwipe?: boolean
Do you mean `disable`?

Also, why use a component called `Swipeable` in the first place if you are not allowed to swipe? Since it's a boolean coming from the outside, the outside should just never call this component

2023-05-16 08:32 UTC, LindvedKrvang commented on src/client/components/shared/switch/switch.tsx
> +    classNames={`${props.classNames ?? 'c-switch'} ${props.checked ? 'on' : ''}`.trimEnd()}
Why do you need to trim?

2023-05-16 08:32 UTC, LindvedKrvang commented on src/client/components/shared/switch/switch.tsx
> +export default function Switch(props: SwitchProps): JSX.Element {
Do you mean a Toggle?

2023-05-16 08:32 UTC, LindvedKrvang commented on src/client/components/tab/tab-title/tab-title.tsx
> +  <div className={`tab-title ${isSelected ? 'active' : ''}`.trimEnd()}
This div is the content of the return, so it should not be on the same indentation as the return. You have done this quite a few places.

2023-05-16 08:32 UTC, LindvedKrvang commented on src/client/components/thumbnail/cued-thumbnail-overlay.tsx
> +export default function CuedThumbnailOverlay(props: CuedThumbnailOverlayProps): JSX.Element {
This component seems like overkill

2023-05-22 06:36 UTC, andr9528 commented on src/client/components/thumbnail/cued-thumbnail-overlay.tsx
> +export default function CuedThumbnailOverlay(props: CuedThumbnailOverlayProps): JSX.Element {
Has been removed, by moving the JSX to the one place it was used.

2023-05-22 06:40 UTC, andr9528 commented on src/client/components/tab/tab-title/tab-title.tsx
> +  <div className={`tab-title ${isSelected ? 'active' : ''}`.trimEnd()}
Have fixed it here, and will try to do so other places too.
One of the next tasks that are to be done is to Add ESLint to the project, which will fix many such errors.

2023-05-22 06:45 UTC, andr9528 commented on src/client/components/shared/switch/switch.tsx
> +export default function Switch(props: SwitchProps): JSX.Element {
Yes i do. Not sure why i ended up using the Xamarin Forms naming.
WIll rename it, not that i know exactly what the difference between a Switch and Toggle is in this case.

2023-05-22 07:02 UTC, andr9528 commented on src/client/components/shared/switch/switch.tsx
> +    classNames={`${props.classNames ?? 'c-switch'} ${props.checked ? 'on' : ''}`.trimEnd()}
Don't technically need it, but it does make the CSS look cleaner if looked at from the Inspect tool.

2023-05-22 07:11 UTC, andr9528 commented on src/client/components/shared/swipeable.tsx
> +  disallowSwipe?: boolean
Appears that i had just forgotten to remove it when i removed hte need for it.
Gone now.

2023-05-22 07:16 UTC, andr9528 commented on src/client/components/offline-overlay/offline-overlay.tsx
> +export default function OfflineOverlay(): JSX.Element {
Removed it, by merging it into the only used location - component-decider.

2023-05-22 07:24 UTC, andr9528 commented on src/client/components/shared/swipeable.tsx
> +  const [touchStart, setTouchStart] = useState<Point | null>(null)
Has done as suggested.

I dislike null / undefined too, but at the very least it is kept contained within this one component, and not bleeding out into others. It is needed in this case as there shoul not be any touched point when the user is not tocuhing the screen.

2023-05-22 07:29 UTC, andr9528 commented on src/client/components/shared/button.tsx
> +    <div onClick={props.onClick} className={props.classNames}>
I believe i had done so originally, but that then needed some CSS to make it match how it looked before / want it to look.
Keeping it as a div made it look as desired from the get-go.

2023-05-22 07:38 UTC, andr9528 commented on src/client/components/settings/output/output.tsx
> +    const tickCss: string = 'settings-tick-field'
Yes i did. Have updated it to say 'checkbox' instead of 'tick' in the variable and css class name.

2023-05-22 07:40 UTC, andr9528 commented on src/client/components/settings/output/output.scss
> +  color: rgb(255, 255, 255);
Updated 4 places in total.

2023-05-22 07:43 UTC, andr9528 commented on src/client/components/settings/output/output.tsx
> +    const fieldCss: string = 'settings-input-field'
Yes? Not sure what is wrong with this.

2023-05-22 07:50 UTC, andr9528 commented on src/client/components/settings/output/output.tsx
> +    const [label, setLabel] = useState(props.outputSettings.label)
Did that at an earlier stage i believe. 

That however then needes to copy all the other properties, not being changed, when changing one property.
Wasn't a fan of having to copy all the other properties when changing one, so i changed it to this setup.
Not sure which is more correct to do...

2023-05-22 08:07 UTC, andr9528 commented on src/client/components/settings/casparcg-settings-form/casparcg-settings-form.tsx
> +            <hr />
Not sure. It is part of the original layout, adding some dividing lines between different elements of the settings page.
I'd be up for either removing it or keeping it, but ultimately i think the PO would beed to get in over this.

2023-05-22 08:23 UTC, andr9528 commented on src/client/components/shared/labelled-text-input/labelled-text-input.tsx
> +export default function LabelledTextInput(props: LabelledTextInputProps): JSX.Element {
The Label was introduced to reduce duplication.
I am open to change it, but i do not want to introduce more duplicated code, if possible.
Also not entirely sure how i'd archieve the line break using CSS only.

Would very much like a talk about this.

2023-05-22 08:32 UTC, andr9528 commented on src/client/components/header/timer/timer.tsx
> +                {timeService.durationToTimeCode(
Have updated two calls to that method that was being done inside the return.
Not entirely sure what effect that have.

Have already made a number of changes that limit amount of times that time changes on the client side, reducing the amount of re-renders.

2023-05-22 08:38 UTC, andr9528 commented on src/client/components/header/control-actions/control-actions.tsx
> +            >LOOP</Switch>
Have updated a number of places for this code styling.
Not sure if i have hit all, but ESLint will clean it up further when installed in one of following tasks.

2023-05-22 08:38 UTC, andr9528 commented on src/client/components/header/action-group/action-group.tsx
> +  <div className={`c-action-group ${props.classNames ?? ''}`.trimEnd()}>
No, but is makes it cleaner to look at in the DevTools.

2023-05-22 08:41 UTC, andr9528 commented on src/client/components/component-decider.tsx
> +export default function ComponentDecider() {
Was unsure what to name it when i created it, but now that you mention 'Body' that is the perfect name.
Have renamed it to 'Body'.

2023-05-22 08:48 UTC, andr9528 commented on src/client/components/header/control-actions/control-actions.scss
> +  font-size: 0.9em;
I am open to change it, but i'd very much like to get an concensus before chainging it, so i don't have to change it multiple times.
At the moment i think most are written using 'px', which also seems to be the most easy one to use. I am fine with either.

Which one you vote for @KvelaGorrrrnio & @RasmusAlbrektsen  ?

2023-05-22 08:49 UTC, andr9528 commented on src/client/components/main.tsx
> +// TODO: possibly find a better name
Got any suggestions?
I wrote that comment, hoping for some suggestion during the PR, as i do not currently know of any good name...

2023-05-31 08:47 UTC, LindvedKrvang commented on src/client/components/main.tsx
> +// TODO: possibly find a better name
Next time, just ask one of us before you commit a TODO

2023-05-31 09:49 UTC, LindvedKrvang commented on src/client/components/settings/output/output.tsx
> +    const fieldCss: string = 'settings-input-field'
It should not be stored in a variable

2023-05-31 10:18 UTC, andr9528 commented on src/client/components/header/action-group/action-group.tsx
> +  <div className={`c-action-group ${props.classNames ?? ''}`.trimEnd()}>
The `.trimEnd()`s have been removed, just a FYI.

2023-05-31 10:27 UTC, andr9528 commented on src/client/components/settings/output/output.tsx
> +    const fieldCss: string = 'settings-input-field'
So you's rather have it placed in 6 places directly? 
Meaning if css applied to those 6 places had to change you'd want to do it 6 times instead of ones?
The 6 areas that use it needs to have the same css, to look the same.

Also they are defined in constants, not variables, or do you mean they should be placed outside of the component, still as constants, but with SNAKE_CASE?

``` typescript
interface OutputProps {
   ... // Cut away the definition
}

const FIELD_CSS: string = 'settings-input-field'
const CHECKBOX_CSS: string = 'settings-checkbox-field'

export default function Output(props: OutputProps): JSX.Element {
   ... // Rest of component
}
```

2023-05-31 11:59 UTC, KvelaGorrrrnio requested changes
We are currently at 134/157 files. This review was also performed by @RasmusAlbrektsen @LindvedKrvang.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/services/browser-service.ts
> +    ORDINARY = 'ordinary',
I don't think `ordinary` is a good choice of word for describing this mode. What is ordinary about it?
I think `default` is an improvement, but ideally this should have a descriptive name that portrays its features – 
e.g. `image`.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/services/browser-service.ts
> +    TEXT = 'textview',
Why is is `textview` and not `text`?

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/services/browser-service.ts
> +}
Correct me if I am wrong, but I don't think that this enum is representative of the true states.
From my understanding `CHANNEL` is a separate option from the two display modes. Shouldn't you be able to have the media files displayed as `TEXT`,  while limiting it to a single channel?

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/services/browser-service.ts
> +    public isOrdinaryView(): boolean {
Spacing between methods would be nice.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/services/browser-service.ts
> +            const specificChannel = channel ? parseInt(channel) || 0 : 0
Are negative numbers allowed?

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/services/browser-service.ts
> +        const search = new URLSearchParams(window.location.search)
Just a note. This class is dependent on the global variable `window`. To make this more flexible, you could define a parameter that takes a `Location` or `string` and use that for extracting.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/services/browser-service.ts
> +export default browserService
I would advice against using default exports. For data structures, this makes the code harder to maintain, since it makes it easy to mistype when importing, and there is a high possibility that the imported name will diverge from the original structure. E.g. you could have something like:

```typescript
// file-a.ts
export default class BrowserService {
  // ...
}

// file-b.ts
import ConsoleService from './file-a.ts'
```

The same applies to exported variables. And in the case where the data structure is renamed, the import might not be. I have seen this firsthand in other projects, which hid issues until it hit production.
For these reasons I will suggest using named exports.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/services/client-handler-service.ts
> +        )
If you use the `this.X.bind(this)` syntax, the methods in this class can be simplified a lot.
```suggestion
        this.socket.on(ServerToClient.FOLDERS_UPDATE, this.processFoldersUpdateEvent.bind(this))
```

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/services/client-handler-service.ts
> +    private initServerEvents(): void {
This function does not initialize server events. It initializes listeners/handlers for server events. Same prinicipal for `initConnectionEvents`.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/services/client-handler-service.ts
> +    socket: SocketIOClient.Socket
The socket should not be public.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/services/client-handler-service.ts
> +        console.log('Client state :', state)
Logging the redux state should not be done here. If something needs to be logged here, then it should be based on the inputs of the method. You can also consider using a logging library, to give your log statements a severity to filter by.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/services/client-handler-service.ts
> +    private processTimeTallyUpdateEvent(data: TimeSelectedFilePayload[]): void {
You should be able to specify the input to something more concrete than `data`.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/services/client-handler-service.ts
> +            this.processSingleTimeTallyPayload(channel, index)
Again, you can use `.bind(this)`, to simplify the expression.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/services/client-handler-service.ts
> +        if (channel.time[0] !== oldTime[0] || channel.time[1] !== oldTime[1]) {
This could be extracted to a function explaining what we are checking for.
And by converting this conditional to a guard, you can eliminate the nesting.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/services/client-handler-service.ts
> +    }
Why would you need to access the socket?

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/services/changing-settings-service.ts
> +        )
If you use this in a render function, you will potentially do a lot of comparing potentially large objects. This could be avoided with dynamic programming, if you compute and store the value when either of the inputs change.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/services/changing-settings-service.ts
> +        reduxStore.dispatch(toggleSettings())
Does `toggleSettings` toggle all settings at once, and how is that handled for non-binary values?
Or does this `toggleSettingsVisibility`?

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/services/changing-settings-service.ts
> +    private updateStateTemporarySettings(
`State` seems unnecessary. You don't decrease the semantic by renaming it to `updateTemporarySettings`.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/services/changing-settings-service.ts
> +class ChangingSettingsService {
It looks like you have multiple responsibilities in this class. You have logic for preparing and applying changes; logic for toggling visibility of a UI component; handling different types of settings.

The logic for prepare-apply is what I recognize at the primary responsibility.  This should be doable without knowing the exact data structure.

Is this component needed? It seems to do the same thing as a form.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/header/action-group/action-group.tsx
> +export default function ActionGroup(props: ActionGroupProps): JSX.Element {
The component is misnamed or misused. You use it to (primarily) style individual buttons and other things that are not "actions".

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/header/action-group/action-group.tsx
> +  classNames?: string
Is it possible to rename this to `className`? And is it needed? In most cases, the alternative styling should be done in the parent component.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/app/app.tsx
> +            </div>
Why do we have a wrapping div around the Body component, which is the application "body"?
And what does `Body` do? A better(?) name would be `ApplicationRouter`.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/body/body.tsx
> +    const isSettingsOpen: boolean = useSelector((state: State) => state.appNavigation.isSettingsOpen)
Some places `visible` is used. This should be streamlined. I vote for `isSettingsVisible`.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/body/body.tsx
> +      return (<div className="offline-overlay">CONNECTING TO SERVER...</div>)
This is used as a page. So it makes sense to make this its own page component.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/footer/operation-mode-edit-visibility-footer/operation-mode-edit-visibility-footer.tsx
> +export function OperationModeEditVisibilityFooter(): JSX.Element {
`OperationMode` can be removed.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/footer/operation-mode-edit-visibility-footer/operation-mode-edit-visibility-footer.tsx
> +            { 'You are currently editing the visibility of files.'.toUpperCase() }
Can we change this to:
```suggestion
            YOU ARE CURRENTLY EDITING THE VISIBILITY OF THE MEDIA FILES.
```

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/footer/operation-mode-footer.tsx
> +export function OperationModeFooter(): JSX.Element {
It seems odd that a component is responsible for determining if it should be displayed or not. If this is handled by the parent, then this component more or less becomes redundant.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/footer/operation-mode-footer.tsx
> +  const activeTab: number = appNavigationService.getActiveTab(state.appNavigation)
Is a tab a number or is this the index of the tab?

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/header/control-actions/control-actions.scss
> +  font-size: 0.9em;
Personally I think that it is fine to use different units for different attributes. But e.g. font-size should not mix px and em/rem.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/header/header/header.tsx
> +export default function Header(): JSX.Element {
`Header` is quite generic, but the implementation is not. Change it to something like `ApplicationHeader`.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/header/timer/timer.tsx
> +        <ActionGroup>
There are no actions inside this `ActionGroup` – hence reinforcing that `ActionGroup` is not correctly named/used.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/header/timer/timer.tsx
> +export default function Timer(): JSX.Element {
This component is more than a timer. It also displays a thumbnail.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/header/timer/timer.tsx
> +    }
This can be changed to a const by using the `or` operator:
```suggestion
    const cleanFileName = settingsService.getCleanSelectedFileName(settingsOutput, state.settings) || cleanFileName = settingsService.getCleanCuedFileName(settingsOutput, state.settings)
```

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/header/timer/timer.tsx
> +        (state: State) => mediaService.getOutput(state.media, activeTab)?.thumbnailList)
By utilizing smart-dumb components, this can be changed to be a single property.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/tab/tab/tab.tsx
> +    <Swipeable className="tab" onSwipe={(direction) => onValidSwipe(direction, props.activeTab, props.totalTabs)}
`Swipeable` should not be on the individual tab. Swipeable should ideally take a list of things to swipe between, so that we can encapsulate all swiping logic inside the Swipeable component.
A good place to use the Swipeable component would be in Tabs.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/tab/tab/tab.tsx
> +  totalTabs: number
A component should not know of things outside of its scope. In this scenario, activeTab, tabIndex and totalTabs indicates that this is part of a sequence and should therefore not be here.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/tab/tab/tab.tsx
> +export default function Tab(props: TabProps): JSX.Element {
This "Tab" component is not generic, and thus the name is not very descriptive.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/main.tsx
> +// TODO: possibly find a better name
After Tab and Tabs have been reworked, this will most likely be easier to determine.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/main.tsx
> +  const tabInfo: TabInfo[] = useSelector((state: State) => settingsService.getTabInfo(state.settings, state.media))
To emphasize that this is multiple pieces of information for tabs, can we rename this to `tabs`. The TabInfo interface should also be changed to `Tab`.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/settings/casparcg-settings-form/casparcg-settings-form.tsx
> +                    wrapperClassName={fieldCss}
We use different approaches for adding class names to custom components. Some places it is this (`wrapperClassName`) and other places it is `classNames`. We should streamline this and is it possible to use `className`?

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/settings/casparcg-settings-form/casparcg-settings-form.tsx
> +    const fieldCss: string = 'settings-input-field'
Why is this class needed?

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/settings/casparcg-settings-form/casparcg-settings-form.tsx
> +                    description="OSC PORT (into ClipTool) :"
We should not have spaces before colons.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/settings/casparcg-settings-form/casparcg-settings-form.tsx
> +        changingSettingsService.saveTemporaryCcgSettingChanges(settings)
This seems overly complex. I hope that this will become simpler when the comments on `ChangingSettingsService` are addressed. Otherwise we will get back to it.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/settings/output/output.tsx
> +    const [label, setLabel] = useState(props.outputSettings.label)
I think we should have a look at this, to see if we can use a single useState.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/settings/output/output.tsx
> +                            }
You change the lambda body to an expression instead of a statement block.
```suggestion
                            (path: string, folderIndex: number) => (
                                <option key={folderIndex} value={path}>
                                    {path}
                                </option>
                            )
```

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/settings/output/output.tsx
> +                                    <option key={folderIndex} value={path}>
You should not use index values for key attributes.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/settings/casparcg-settings-form/casparcg-settings-form.tsx
`-form` is an implementation detail that should not be reflected in the name. Same goes for the scss file.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/settings/outputs.tsx
> +                            key={index}
Index values should not be used for key attributes.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/settings/outputs.tsx
> +                        (item, index) => <Output configChannel={item}
`<Output configChannel={item}` should be moved to next line. It would be nice to have a PR after this with only linting.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/settings/outputs.tsx
> +                        (item, index) => <Output configChannel={item}
And item is not descriptive. Please name it after what it is.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/main.tsx
> +        {tabInfo.map((data, index) =>
To emphasize that this is multiple pieces of information for tabs, can we rename this to `tabs`. The TabInfo interface should also be changed to `Tab`.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/settings/settings-actions/settings-actions.tsx
> +  const buttonCss = "save-button"
You are using this for multiple buttons that doesn't match the class name whatsoever.
There should be a better way to style the buttons.

We should not have this variable. If you have multiple related components that are in need of some common styling, either the parent component should be responsible or a new component should emerge.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/settings/settings-actions/settings-actions.tsx
> +function emitSetOperationModeToEditVisibility(): void {
`emit` is an implementation detail of the SocketService that this component should have no knowledge about.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/settings/settings/settings.tsx
> +        }
```suggestion
        return () => changingSettingsService.resetStateHandler()
```

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/shared/button.tsx
> +    <div onClick={props.onClick} className={props.classNames ?? ''}>
Why is it a div and not a button? You lose a lot of functionality by not using a button.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/shared/button.tsx
> +  children?: React.ReactNode
This allows for inserting an entire page or an application inside a button, which should not be possible. A button should only display text, and if you need a more fancy button, like an image button, then you make an ImageButton component.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/shared/checkbox-input/checkbox-input.tsx
> +  value: boolean
Instead of calling this value, you could call it `checked`.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/shared/checkbox-input/checkbox-input.tsx
> +export default function CheckboxInput(props: CheckboxInputProps): JSX.Element {
Input is redundant. The component should be called Checkbox.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/shared/checkbox-input/checkbox-input.tsx
> +  inputClassName?: string
These should be removed. If you need variations, make components for them.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/shared/label/label.tsx
> +export default function Label(props: LabelProps): JSX.Element {
What is the purpose of this component, that is not accomplished in e.g. the CheckboxInput component?

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/shared/switch/toggle.tsx
> +export default function Toggle(props: ToggleProps): JSX.Element {
This should still be called `Switch`.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/tab/tab-title/tab-title.tsx
> +}
This should not be the responsibility of the TabTitle component. It should be the parent/smart component.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/tab/tabs/tabs.tsx
> +        <div className='tabs-bar__tabs'>
You are not showing tabs in this container. You are showing the tab titles.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/tab/tabs/tabs.tsx
> +            const childProps = child.props as any as TabProps
Instead of casting, you should enforce a stricter type on the childrens property. Also you conform your runtime values to a type that they are not compatible with.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/tab/tabs/tabs.tsx
> +            return (<TabTitle key={index} title={childProps.title} tabIndex={index} selectedTab={selectedTab}/>)
Don't use index values for key attributes.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/thumbnail/image-thumbnail/image-thumbnail.tsx
> +  ) ?? {}
Why is the nullish coalescing happening outside the useSelector? And is it necessary?

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/thumbnail/image-thumbnail/image-thumbnail.tsx
> +                .slice(-45)}
Please move this to a function with a descriptive name.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/thumbnail/text-thumbnail/text-thumbnail.tsx
> +export default function TextThumbnail(props: TextThumbnailProps): JSX.Element {
This name is misleading. Thumbnail indicates that it has the media thumbnail, but it doesn't. Instead this could be called a `TextMediaCard`. And then the ThumbnailButton should be renamed to `MediaCard`.

An alternative is to get rid of ThumbnailButton and then just have `TextMediaCard` and `ImageMediaCard`.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/thumbnail/thumbnail-button/thumbnail-button.tsx
> +}
All of this functionality should not be on the button. This limits the use cases for the component. It should be the smart/parent component which is responsible for this logic.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/thumbnail/thumbnail-overlay-display/thumbnail-overlay-display.tsx
> +  }
This can be reduced to
```suggestion
  const isValidFile = isSelected ? mediaService.isValidFile(props.file, time) : false
```

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/thumbnail/thumbnail-overlay/thumbnail-overlay.tsx
> +    <a className={`thumbnail-overlay ${props.classNames ?? ''}`}>
Why is this an anchor?

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/thumbnail/thumbnail-overlay/thumbnail-overlay.tsx
> +  classNames?: string
You should not use classNames as a way to target local css classes like `selected` and `cued`. These should be properties.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/thumbnail/thumbnail-picture/thumbnail-picture.scss
> +.thumbnail-picture {
We should streamline the use of image and picture. Let us use image.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/thumbnail/thumbnail-picture/thumbnail-picture.tsx
> +export default function ThumbnailPicture(props: ThumbnailPictureProps): JSX.Element {
This seems like overkill to have a component to return an img.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/thumbnail/thumbnails/thumbnails.tsx
> +export function Thumbnails(): JSX.Element {
Again, thumbnail is misleading. This could be changed to `MediaOverview`.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/thumbnail/thumbnails/thumbnails.tsx
> +        : files
This could be moved out into its own function.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/components/thumbnail/thumbnails/thumbnails.tsx
> +        <div className="thumbnails-region">
The class name should be the same as the component name.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/index.tsx
> +console.log('Redux initialized :', state)
Consider adding a logger to differentiate between different severities of log statements.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/services/browser-service.ts
> +class BrowserService {
If we use a router to define search parameters, this class will be redundant.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/services/client-handler-service.ts
> +class ClientHandlerService {
Service is redundant. And perhaps this should be called something along the lines of `BackendApi`.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/services/event-service.ts
> +// TODO: Come up with a better name.
What kind of events are handled here? And is the class necessary?

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/client/services/socket-service.ts
> +class SocketService {
Instead of accessing the socket directly. You could make a triade of classes: `SocketConnection`, which is responsible for the connection; `BackendApi` which is responsible for sending commands to the backend (via the `SocketConnection`; `BackendObserver`, which is responsible for reacting to the changes that is received in the SocketConnection.

Currently we know everywhere in the code that we are using sockets to speak to the backend, which is not ideal. That will also encourage not prefix all the methods with `emit`, since that is an implementation detail.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/model/reducers/app-navigation-action.ts
> +        tabIndex: tabIndex,
You can use shorthand notation:
```suggestion
        tabIndex,
```

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/model/reducers/app-navigation-action.ts
> +        isConnected: isConnected,
You can use shorthand notation:
```suggestion
        isConnected,
```

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/model/reducers/media-models.ts
The models are not part of the reducer. It might be that the reducers are dependent on the model.
Instead of calling this folder model, then call it shared. Then you can have reducers and data models separated.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/model/reducers/media-reducer.ts
> +    })
This is not an ideal setup. If you change the attribute for one index, you change it for them all. This will be an array of pointers to the same object.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/model/reducers/settings-models.ts
> +export interface CcgConfig {
Would be nice if we don't use abbreviations.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/model/schemas/old-settings-schema.ts
> +            arrayService.fillWithDefault(transform, false)
What is wrong with `Array(amount).fill(value)`?

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/model/services/array-service.ts
> +            array.push(defaultValue)
If an object is given as the defaultValue, then a list of x references to that object will be created.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/model/services/media-service.ts
> +class MediaService {
Why is it not exported?

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/model/services/media-service.ts
> +            (predicate) => predicate.name === cleanFileName
Rename predicate to `mediaFile`.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/model/services/os-service.ts
> +    getThisMachineIpAddresses(): string[] {
I know that it is not you who named this, but this could be renamed to `getIpAddresses`.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/model/services/os-service.ts
> +class OsService {
What is Os?

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/model/services/reducer-service.ts
> +class ReducerService {
What does this reducer reduce?

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/model/services/settings-service.ts
> +            outputSettings: Array(8).fill(defaultOutputSettingsState),
Remember that this creates an array with 8 references to defaultOutputSettingsState.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/model/services/settings-service.ts
> +            .fill({})
The curly braces are not necessary.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/model/services/settings-service.ts
> +                }
This could be extracted to its own method.

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/model/schemas/new-settings-schema.ts
> +export const NewGenericSettings = z.object({
Why is this capitalized and why does it not have the Schema suffix? And what is the purpose of it?

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/model/services/settings-service.ts
> +    public isThumbnailCued(
Is it the thumbnail which is cued or the media?

2023-05-31 11:59 UTC, KvelaGorrrrnio commented on src/model/services/settings-service.ts
> +        return cleanSelectedFileName
This should be returned directly.

2023-05-31 11:59 UTC, KvelaGorrrrnio requested changes
We are currently at 134/157 files. This review was also performed by @RasmusAlbrektsen @LindvedKrvang.

2023-05-31 12:26 UTC, andr9528 commented on src/model/services/settings-service.ts
> +        return cleanSelectedFileName
Done that now.

2023-05-31 12:30 UTC, andr9528 commented on src/model/services/settings-service.ts
> +    public isThumbnailCued(
Good point. It is the video file that is loaded (cued), but the thumbnail that is clicked to do so. 
It is also on the thumbnail that the indicator of it being cued or not, is shown, which might be why i named it like that.

Have renamed it to `isMediaCued()`.

2023-05-31 12:36 UTC, andr9528 commented on src/model/schemas/new-settings-schema.ts
> +export const NewGenericSettings = z.object({
The capitalization is a mistake by me when i used an online tool to convert the typescript interface to the zod schema. Same for missing the Schema suffix. Has been fixed now.

As for its usage, it is used to verify that the settings loaded from the json file matches the code structure. On top of this it enriches the loaded settings with defaults, if no value for different attributes are found.

2023-05-31 12:41 UTC, andr9528 commented on src/model/services/settings-service.ts
> +                }
Done that now. Not sure if name of the new method is good (`buildTabInfoForIndex(...)`), but the best i could come up with at the moment of writting it.

2023-05-31 12:43 UTC, andr9528 commented on src/model/services/settings-service.ts
> +            .fill({})
_Expected 1-3 arguments, but got 0_

Code seems to disagree with you. I also originally tried without the curly braces.

2023-05-31 12:56 UTC, andr9528 commented on src/client/services/browser-service.ts
> +    TEXT = 'textview',
It is `textview`, as that is what gets written in the search bar, and 2/3 of the enum values doubles as the text that i locked for in the search parameters.

If it was to be changed, then i'd either have to create a new enum, containing the values used in the search bar, and one for what we want to store in the program. Or we'd need to change the search parameter name together with the enum value, which would then need to be explained and updated on a number of places Cliptool is used,
Thought with how i'd done, we'd have the lowest amount of code, with the least amount of changes in the physical production setups.

2023-05-31 13:02 UTC, andr9528 commented on src/client/services/browser-service.ts
> +    ORDINARY = 'ordinary',
Hmm, in the Functional Test i reference this view as the 'Main' view, which isn't very descriptive either. In the Functional tests i decribe early on, that when that term is mentioned, it means the view accessed by the parameterless search (http://localhost:5555/).

Would 'Main' be a good/okay term to use here?

2023-05-31 13:03 UTC, andr9528 commented on src/client/services/browser-service.ts
> +    public isOrdinaryView(): boolean {
Done that now.

2023-05-31 13:12 UTC, andr9528 commented on src/client/services/browser-service.ts
> +}
Hmm, didn't consider this. 

Will need to investigate if this was something you could do before, and/or ask Kevin is this is something you are suppose to be able to do.

Have made a note for myself, to look into it.

2023-05-31 13:20 UTC, andr9528 commented on src/client/services/browser-service.ts
> +            const specificChannel = channel ? parseInt(channel) || 0 : 0
No they are not, and now that i think abit about it, the channels are 1-indexed in the search bar, which gets turned into a 0-indexed by the `getChannel()` method, when it finaly gets used.

Have changed it, such that if a value of 0 or lower is passed, 1 is the chosen value.
`const specificChannel = channel ? Math.max(parseInt(channel), 1) : 1`.

2023-05-31 13:24 UTC, andr9528 commented on src/client/services/browser-service.ts
> +        const search = new URLSearchParams(window.location.search)
Have changed it such that the constructor takes a string input. 
Also better opens up the service class for Unit Tests later down the line.

2023-05-31 13:44 UTC, andr9528 commented on src/client/services/browser-service.ts
> +export default browserService
This one took me a long time to understand. What you are saying is that when importing a default export you could write 'horse', and it would be completely fine, and just alias the imported default as what ever was written.

That appear to only really be an issue if you are manually writting the imports, and not getting the Intellisense to insert the import for you.

I have a suspicion that this one was pointed out by Lindved, Regardless of who, i'd like to have a talk about it. 
If changes in regard to this has to be made, then it is EVERY file that is going to have changes again, afaik.

2023-05-31 13:49 UTC, andr9528 commented on src/client/services/client-handler-service.ts
> +        )
I don't fully grasp when 'this' is what in different typescript code yet.
Before applying the suggested change, i'd like a more indepth explanation of the suggested change.
Could we have talk about it?

2023-05-31 14:28 UTC, KvelaGorrrrnio requested changes
Rest of the files have been gone through. Reviewed by @KvelaGorrrrnio and @RasmusAlbrektsen.

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/model/services/time-service.ts
> +        durations: [number, number] = [0, 0],
This should be named `timeRange` since it is start time and end time.

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/model/services/time-service.ts
> +        }
This should not be a part of the shared code. If you need specific logic for the client, then make another service that wraps around this one.

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/model/services/time-service.ts
> +        const time = Math.max(0, durations[1] - durations[0])
This should be called `duration`.

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/model/services/time-service.ts
> +    private leadingZero(num: number, length: number = 2): string {
Should be `addLeadingZeros`.

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/model/services/time-service.ts
> +    public durationToTimeCode(
Should be `convertDurationToTimeCode`.

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/model/services/time-service.ts
> +class TimeService {
Why isn't this exported?

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/model/socket-io-constants.ts
> +export enum ServerToClient {
Server to client what? Commands?
Same goes for ClientToServer enum.

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/model/socket-io-constants.ts
> +    THUMBNAIL_UPDATE = 'thumbUpdate',
All of these values should be changed to lowercase kebab-casing and should be representative of the key. E.g.: `THUMBNAIL_UPDATE = 'thumbnail-update'`.

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/server/index.ts
> +process.on('unhandledRejection', (error) => processUnhandledRejection(error))
I remember that you used it for testing. It should be removed for production.

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/server/services/hidden-files-persistence-service.ts
> +                this.validateHiddenFiles(hiddenFilesFromFile)
There is a mismatch between variable name and expression call.

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/server/services/hidden-files-persistence-service.ts
> +            const hiddenFilesFromFile: Record<string, HiddenFileInfo> =
This should just be `hiddenFiles`.

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/server/services/hidden-files-persistence-service.ts
> +class HiddenFilesPersistenceService {
Why is it not exported?

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/server/services/hidden-files-persistence-service.ts
> +            if (isInvalidHiddenFiles) {
This seems wrong....

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/server/services/hidden-files-persistence-service.ts
> +                    'File containing hidden files not found, or not yet stored.'
This function should be divided into two, such that you can give an accurate error message.

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/server/services/hidden-files-persistence-service.ts
> +            this.getCleanHiddenFiles(hiddenFiles)
I am not a fan of us depending directly on the global state variable. Why not just take the hiddenFiles as an argument?

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/server/services/hidden-files-persistence-service.ts
> +        persistenceService.saveFile(
Why is this done as a callback?

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/server/services/hidden-files-persistence-service.ts
> +            (error: any) => {
Why is the error any type?

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/server/services/hidden-files-persistence-service.ts
> +            this.validateHiddenFiles(originalHiddenFiles)
This seems to happen way to much in this flow.

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/server/services/hidden-files-persistence-service.ts
> +    private validateHiddenFiles(
It is not plain to see from the method name what it checks for.
A better name could be `hasSelectedHiddenFiles`.

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/server/services/hidden-files-persistence-service.ts
> +    private clearInvalidHiddenFiles(
`clear` does not indicate that the cleansed hidden files are returned.
A better name could be `getValidHiddenFiles`.

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/server/services/persistence-service.ts
> +const path = require('path')
Why aren't these `import`'ed?

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/server/services/persistence-service.ts
> +class PersistanceService {
Why is this not exported?

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/server/services/persistence-service.ts
> +        file: string,
What are the difference?

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/server/services/persistence-service.ts
> +        if (!fs.existsSync('storage')) {
Why not use the promise-based functions?

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/server/services/settings-persistence-service.ts
> +class SettingsPersistenceService {
Why is it not exported?

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/server/services/settings-persistence-service.ts
> +            const isOld = this.isPreviousStructure(settingsFromFile)
`isOld` is vague. What is old?

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/server/services/settings-persistence-service.ts
> +            const isOld = this.isPreviousStructure(settingsFromFile)
This flow should be altered. Check for the new format first, and if that fails, then the old. It will also be beneficial to split the method up such that the flow becomes something like:
```typescript
function load(): void {
  const rawSettings: unknown = JSON.parse(......)
  try {
    const settings = this.getSettings(rawSettings)
    this.save()
  } catch (error) {
    this.logger.......
  }
}

function getSettings(rawSettings: unknown): Settings {
    if (this.isNewStructure(rawSettings)) {
      return this.parseNewStructure(rawSettings)
    }
    if (this.isOldStructure(rawSettings)) {
      return this.parseOldStructure(rawSettings)
    }
    return defaultGenerics
}

2023-05-31 14:28 UTC, KvelaGorrrrnio commented on src/server/services/settings-persistence-service.ts
> +    private isPreviousStructure(loadedFile: any): {
The name here indicates that a boolean is returned. That is not true. Either the name or the method should be changed.
The argument should have a better name, e.g. `maybeSettings` or `rawSettings`.

2023-06-01 06:52 UTC, andr9528 commented on src/client/services/client-handler-service.ts
> +    socket: SocketIOClient.Socket
Fixed

2023-06-01 06:54 UTC, andr9528 commented on src/client/services/client-handler-service.ts
> +    private initServerEvents(): void {
Added 'Listeners' to the end of both method names.

2023-06-01 06:59 UTC, andr9528 commented on src/client/services/client-handler-service.ts
> +        console.log('Client state :', state)
I think Anders and I, have talked about that when the Frontend and Backend gets split into seperate programs (UT-203), we would be applying TV2 logging framework that is already being used on the backend, to the frontend side too.

For now i have just removed the log statement. 
When the logging framework is used, it might be good to re-add it as a debug or trace level.

2023-06-01 07:02 UTC, andr9528 commented on src/client/services/client-handler-service.ts
> +    private processTimeTallyUpdateEvent(data: TimeSelectedFilePayload[]): void {
Renamed it to `payloads`. 
If that name is not sufficent then it might just need to be `timeSelectedFilePayloads`, but that doesn't really roll of the tungue.

2023-06-01 07:04 UTC, andr9528 commented on src/client/services/client-handler-service.ts
> +            this.processSingleTimeTallyPayload(channel, index)
And again before applying it (which i want to), i want to better understand what that does.

2023-06-01 07:12 UTC, andr9528 commented on src/client/services/client-handler-service.ts
> +        if (channel.time[0] !== oldTime[0] || channel.time[1] !== oldTime[1]) {
Has been extracted to a new method with the name `hasTimeChanged`, and been inverted to guard, instead of nest.

2023-06-01 07:19 UTC, andr9528 commented on src/client/services/client-handler-service.ts
> +    }
Because it is the same socket that is emittet on when sending events to the backend. i.e the SocketService uses it.

It has in total 2 places where it is called. First the SocketService, as mentioned, and secondly in the index.tsx, where it just gets logged.
This call is mainly there to ensure that the ClientHandlerService is instantiated early enough that everything else shows up as it should.

2023-06-01 07:21 UTC, LindvedKrvang commented on src/client/services/socket-service.ts
> +class SocketService {
Just to clarify, we don't want an actual class named `BackendApi`. We want classes for specific aspects of the backend.
If we have a backend where we can create and update Cars and Drivers then we would want one class called `CarService` that handles all communication with the backend when it comes to Cars. And another file called `DriverService` that handles all communication with the backend when it comes to Drivers. Both of these files will be utilizing the `SocketConnection` etc.

2023-06-01 07:49 UTC, andr9528 commented on src/client/services/changing-settings-service.ts
> +        )
If i understood it correctly, you suggested to introduce a private class attribute, wherein the hasChanges boolean value is stored. This `hasChanges` value will then be updated when changing either of the inputs. In the render function i will just get the stored value. 

If i understood that correctly, then i have now made that change.

2023-06-01 07:51 UTC, andr9528 commented on src/client/services/changing-settings-service.ts
> +        reduxStore.dispatch(toggleSettings())
It toggles the settings page visibility. Have renamed the method.

2023-06-01 07:53 UTC, andr9528 commented on src/client/services/changing-settings-service.ts
> +    private updateStateTemporarySettings(
Have removed `State` from the name.

2023-06-01 08:16 UTC, andr9528 commented on src/client/services/changing-settings-service.ts
> +class ChangingSettingsService {
The main reason this service was introduced and is used, is so that a few settings related actions can be performed from outside the settings page, e.g from the header. The main one i will point out is the `discardSettings()` method, which gets called when the `Settings` button in the header is clicked, while settings is open.

Much of what this service class does could likely be done using a form, as you mention. How exactly i am not entirely sure though. With the need to call `discardSettings()` from outside the settings page, i do not know how it would have been archieved without a service class of sorts. It would have needed some form of callback, which would have needed to be passed up and down multiple levels, which sounds tedious/ugly.

2023-06-01 08:23 UTC, andr9528 commented on src/client/components/header/action-group/action-group.tsx
> +export default function ActionGroup(props: ActionGroupProps): JSX.Element {
Hmm you are right, it is used to group together the child elements, which happens to be buttens in 9/10 of the usage, but this one doesn't know that.

Have updated it to just be called `Group`. 
Haven't moved it out of the header folder, but with this more general use name, it might make sense to move it to shared folder, even though it is only in the header that it is used. Should it be moved?

2023-06-01 08:27 UTC, andr9528 commented on src/client/components/header/action-group/action-group.tsx
> +  classNames?: string
Have renamed it to `className`.

It is needed, as it is used to add a right margin to the last element of the header. 
Don't think that could be archieved without the prop input.

2023-06-01 08:31 UTC, andr9528 commented on src/client/components/body/body.tsx
> +    const isSettingsOpen: boolean = useSelector((state: State) => state.appNavigation.isSettingsOpen)
have renamed the constant here and the value on the state to `isSettingsVisible`.

2023-06-01 08:33 UTC, andr9528 commented on src/client/components/body/body.tsx
> +      return (<div className="offline-overlay">CONNECTING TO SERVER...</div>)
Lindved would like to object...

It was origianlly its own component, but he complained that i could very well be inserted directly in the one place it was used, which i then did.

2023-06-01 08:44 UTC, andr9528 commented on src/client/components/app/app.tsx
> +            </div>
Have renamed the `Body` component to `ApplicationRouter`.

The wrapping div was there to ensure that the area fills the available space.
Seems like it isn't needed any longer. Have removed it.

2023-06-01 08:52 UTC, andr9528 commented on src/client/components/footer/operation-mode-edit-visibility-footer/operation-mode-edit-visibility-footer.tsx
> +export function OperationModeEditVisibilityFooter(): JSX.Element {
`OperationMode` has been removed from the name.

2023-06-01 08:54 UTC, andr9528 commented on src/client/components/footer/operation-mode-edit-visibility-footer/operation-mode-edit-visibility-footer.tsx
> +            { 'You are currently editing the visibility of files.'.toUpperCase() }
Done. 

Was just lazy and didn't want to rewrite it in all caps when i chose to add the `toUpperCase()`.
Thanks for writting it in all caps for me :P

2023-06-01 09:02 UTC, andr9528 commented on src/client/components/footer/operation-mode-footer.tsx
> +export function OperationModeFooter(): JSX.Element {
Say 1-∞ more operation modes are added. 
Would you want the logic to decide which to show to be in the parent? or tucked away neatly in this component?

This component was originally build together with Anders, so it can't be all bad, right?
Since Anders and I created it, i think the only addition i have made is that while on the Text View other operation modes are not applied,

2023-06-01 09:11 UTC, andr9528 commented on src/client/components/footer/operation-mode-footer.tsx
> +  const activeTab: number = appNavigationService.getActiveTab(state.appNavigation)
Ah right, it is the index of the active tab. Added `Index` at the end.
Also added it to the end of the method name.

... And updated 50+ other areas with a similar naming inconsistency. Everywhere where `activeTab` was mentioned was always the index of the active tab. Now they all should reflect that.

2023-06-01 09:19 UTC, andr9528 commented on src/client/components/header/header/header.tsx
> +export default function Header(): JSX.Element {
Has been renamed to `ApplicationHeader`.

2023-06-01 09:19 UTC, andr9528 commented on src/client/components/header/timer/timer.tsx
> +        <ActionGroup>
`ActionGroup` has been renamed to `Group`.

2023-06-01 09:26 UTC, andr9528 commented on src/client/components/header/timer/timer.tsx
> +export default function Timer(): JSX.Element {
Not sure if this is sufficent, but have renamed it to `TimerThumbnail`.
That name, coincidentally, also matches with the order of what it renders. First a timer, then a Thumbnail.

2023-06-01 09:27 UTC, andr9528 commented on src/client/components/header/timer/timer.tsx
> +    }
Done that now.

2023-06-01 09:33 UTC, andr9528 commented on src/client/components/header/timer/timer.tsx
> +        (state: State) => mediaService.getOutput(state.media, activeTab)?.thumbnailList)
I am open for changing this, but i'd need a more concrete explanation as to how this here would be deconstructed to use smart-dumb components.

Lets have a talk about it.

2023-06-01 09:42 UTC, andr9528 commented on src/client/components/tab/tab/tab.tsx
> +    <Swipeable className="tab" onSwipe={(direction) => onValidSwipe(direction, props.activeTab, props.totalTabs)}
I think i get what you mean, but i will need a few days to think up how exactly the code would need to be changed.

A chat about this could help.

2023-06-01 09:45 UTC, andr9528 commented on src/client/components/tab/tab/tab.tsx
> +  totalTabs: number
This ties into the `Swipeable` that i am going to have a think about how to alter. 
I understand the need, just need to figure out how.

2023-06-01 09:54 UTC, andr9528 commented on src/client/components/tab/tab/tab.tsx
> +export default function Tab(props: TabProps): JSX.Element {
I get what is said, just don't currently have a better name.
I am open for suggestions...

2023-06-01 09:58 UTC, andr9528 commented on src/client/components/main.tsx
> +  const tabInfo: TabInfo[] = useSelector((state: State) => settingsService.getTabInfo(state.settings, state.media))
have renamed the const to `tabs`, but i am waiting on renaming the interface, as it will othewise name conflict with the Tab component, which i need to find a new name for beforehand.

2023-06-01 10:33 UTC, andr9528 commented on src/client/components/settings/casparcg-settings-form/casparcg-settings-form.tsx
> +                    wrapperClassName={fieldCss}
Have changed areas where i had `classNames`, to without plural.
Have removed a few unused props for applying additional CSS.

There are now only one component that takes in two different set of CSS class names. 
Other than in that one, all props that take in CSS class names are called `className`.

2023-06-01 10:39 UTC, andr9528 commented on src/client/components/settings/casparcg-settings-form/casparcg-settings-form.tsx
> +    const fieldCss: string = 'settings-input-field'
... To apply styling to the inputs?
That css class name is imported from 'shared-settings.scss'

2023-06-01 10:43 UTC, andr9528 commented on src/client/components/settings/casparcg-settings-form/casparcg-settings-form.tsx
> +                    description="OSC PORT (into ClipTool) :"
Hmm, that is how it has always been, afaik.

Might be Okay to remove the spaces, but i am not sure. 
Might be a conscious decision that has been made earlier.

2023-06-01 11:09 UTC, andr9528 commented on src/client/components/settings/casparcg-settings-form/casparcg-settings-form.tsx
> +        changingSettingsService.saveTemporaryCcgSettingChanges(settings)
I think i asked for a chat about the `ChangingSettingsService`, in turn this should propably also be discussed.

~As for the complexity, i think most of it steems from having to create new object every time, to ensure that we don't mutate, as we need to trigger a re-render of settings.~

As i wrote the above, i got to thinking, and realised that it didn't need to create new objects, as it was already disconnected from the ReduxState. I also realised that with how the setup is, that when a change happens to any input on settings, all of settings is re-rendered, so i could make all the sub-components of settings into dump-components.

Those changes removed 2/5 of the lines in the change event handler in the commented on file, along with removing the `useState()`. In the `output.tsx` file each change handler got 1/4 of their lines removed, and again got rid of `useState()`.

Dunno if you still want more changes, and/or want a chat about it.

2023-06-01 11:12 UTC, andr9528 commented on src/client/components/settings/output/output.tsx
> +                            }
Fixed

2023-06-06 06:25 UTC, andr9528 commented on src/client/components/settings/output/output.tsx
> +                                    <option key={folderIndex} value={path}>
Has been changed to use the `path` as key.

2023-06-06 06:27 UTC, andr9528 commented on src/client/components/settings/casparcg-settings-form/casparcg-settings-form.tsx
`-form` has been removed from the name.

2023-06-06 06:54 UTC, andr9528 commented on src/client/components/settings/outputs.tsx
> +                            key={index}
Changed key to use the `label` of the `outputSettings`.

Label can technically be the same, but users are unlikely to do so, as it will look confusing.

2023-06-06 07:01 UTC, andr9528 commented on src/client/components/settings/outputs.tsx
> +                        (item, index) => <Output configChannel={item}
Has been renamed to `channel`, when i reworked how it was setup, to lower duplication.

2023-06-06 07:03 UTC, andr9528 commented on src/client/components/settings/outputs.tsx
> +                        (item, index) => <Output configChannel={item}
Has been moved to new line, as i reworked the code to lower duplication. Unsure if the new setup for the code is good, as there is technically multiple components per file.

2023-06-06 10:38 UTC, andr9528 commented on src/client/components/tab/tab/tab.tsx
> +  totalTabs: number
Tab no longer has any inputs, and instead only add some css to the displayed thumbnails.

2023-06-06 10:43 UTC, andr9528 commented on src/client/components/tab/tab/tab.tsx
> +    <Swipeable className="tab" onSwipe={(direction) => onValidSwipe(direction, props.activeTab, props.totalTabs)}
`Swipeable` are now being applied to `Tabs` rather than `Tab`, taking in an array of `JSX.Element`.

This also eliminates the `swipe-service`, as all the swipe logic has been moved to the swipeable.tsx.

2023-06-06 12:38 UTC, andr9528 commented on src/client/components/main.tsx
> +        {tabInfo.map((data, index) =>
The `tabInfo` constant has been renamed to `tabs`. The `TabInfo` interface has not been renamed, as it would conflict with the `Tab` component, that i do not know a better name for.

2023-06-06 12:42 UTC, andr9528 commented on src/client/components/settings/settings-actions/settings-actions.tsx
> +  const buttonCss = "save-button"
Have renamed it to `c-settings-actions-button`. 

Would like to have a talk about the styling of related components, as i have the same issue in 1-2 other places.

2023-06-06 12:44 UTC, andr9528 commented on src/client/components/settings/settings-actions/settings-actions.tsx
> +function emitSetOperationModeToEditVisibility(): void {
`emit` has been removed from the name.

2023-06-06 12:45 UTC, andr9528 commented on src/client/components/settings/settings/settings.tsx
> +        }
Done

2023-06-06 12:50 UTC, andr9528 commented on src/client/components/shared/button.tsx
> +    <div onClick={props.onClick} className={props.classNames ?? ''}>
The default style of a `button` has some styling that should not be there in any of the places currently used. 
By just using a `div`, i avoid having to add the extra css styling to remove the unwanted styling.

Not sure which is the correct thing to do.
Also what functionality is lost?

2023-06-06 13:23 UTC, andr9528 commented on src/client/components/shared/button.tsx
> +  children?: React.ReactNode
Has been reduced to only take a string as the child. The used `Button` in `ThumbnailButton` has been changed to a `div`

2023-06-06 13:24 UTC, andr9528 commented on src/client/components/shared/button.tsx
> +    <div onClick={props.onClick} className={props.classNames ?? ''}>
When looking into it, it appears that only one extra css line was needed, so i have changed it to use a `button`.

Still would like to know what functionality is lost when using a `div` over a `button`.

2023-06-06 13:25 UTC, andr9528 commented on src/client/components/shared/checkbox-input/checkbox-input.tsx
> +  value: boolean
Done that now. Was leftover from copying `text-input`.

2023-06-06 13:28 UTC, andr9528 commented on src/client/components/shared/checkbox-input/checkbox-input.tsx
> +export default function CheckboxInput(props: CheckboxInputProps): JSX.Element {
Renamed to `Checkbox`.

2023-06-06 13:28 UTC, andr9528 commented on src/client/components/shared/checkbox-input/checkbox-input.tsx
> +  inputClassName?: string
Removed unused, and renamed leftover to `className`.

2023-06-07 06:46 UTC, andr9528 commented on src/client/components/shared/switch/toggle.tsx
> +export default function Toggle(props: ToggleProps): JSX.Element {
Lindved commented and asked if i ment `Toggle`, when it originally said `Switch`. Just forgot to rename the folder too. 
Have however renamed it back to `Switch` as requested.

2023-06-07 06:53 UTC, andr9528 commented on src/client/components/shared/label/label.tsx
> +export default function Label(props: LabelProps): JSX.Element {
The Checkbox component (and TextInput/NumberInput) all originally used the Label as part of their structure.
Lindved disliked that however, so that usage was removed.

It is still used to display/label some of the settings for outputs, adding in a uniform styling between different components.

2023-06-07 07:19 UTC, andr9528 commented on src/client/components/tab/tab-title/tab-title.tsx
> +}
That functions has been moved to the parent, and the function is then parsed in via the props. The `TabTitle` is no longer smart either.

2023-06-07 07:22 UTC, andr9528 commented on src/client/components/tab/tabs/tabs.tsx
> +            const childProps = child.props as any as TabProps
1. I wanted/tried to enforce a stricter type on the child elements, bug couldn't figure out how.
2. The commented on line has been removed in the restructureing of the the tabs.

2023-06-07 07:24 UTC, andr9528 commented on src/client/components/tab/tabs/tabs.tsx
> +        <div className='tabs-bar__tabs'>
Have renamed the class name to `tabs-bar__tab-titles`

2023-06-07 07:25 UTC, andr9528 commented on src/client/components/tab/tabs/tabs.tsx
> +            return (<TabTitle key={index} title={childProps.title} tabIndex={index} selectedTab={selectedTab}/>)
Has been changed to use the title instead.
Users can in theory make the same titles, but i reckon it is unlikely that users do so.

2023-06-07 07:52 UTC, andr9528 commented on src/client/components/thumbnail/image-thumbnail/image-thumbnail.tsx
> +  ) ?? {}
Doing the nullish coalescing inside the `useSelector` or outside has the same effect, so it should just look cleanner.
On the other hand, it appears to not be necessary, so i have removed it.

2023-06-07 07:54 UTC, andr9528 commented on src/client/components/thumbnail/image-thumbnail/image-thumbnail.tsx
> +                .slice(-45)}
As the commented on code was duplicated in `TextThumbnail`, it has now been moved to a new component called - FileNameDisplay.

2023-06-07 08:10 UTC, andr9528 commented on src/client/components/thumbnail/text-thumbnail/text-thumbnail.tsx
> +export default function TextThumbnail(props: TextThumbnailProps): JSX.Element {
- `TextThumbnail` renamed to `TextMediaCard`.
- `ImageThumbnail` renamed to `ImageMediaCard`.
- `ThumbnailButton` renamed to `MediaCard`

Getting rid of `MediaCard` would mean that all the logic inside it would need to be moved to the parent components, which would be ALOT of duplication.

2023-06-07 08:18 UTC, andr9528 commented on src/client/components/thumbnail/thumbnail-button/thumbnail-button.tsx
> +}
This component is now called `MediaCard`.

If the functionality where to still be moved out to the parent, then it would also need to be duplicated completely, as there are two components that use this one, that act eactly the same, just look different.

Have removed `emit` from the name of the functions.

If i am not mistaken then the use of the `useSelector` makes this component into a smart component, which again means that it makes sense for the logic to be here.

2023-06-07 08:20 UTC, andr9528 commented on src/client/components/thumbnail/thumbnail-overlay-display/thumbnail-overlay-display.tsx
> +  }
Done that now.

2023-06-07 08:24 UTC, andr9528 commented on src/client/components/thumbnail/thumbnail-overlay/thumbnail-overlay.tsx
> +    <a className={`thumbnail-overlay ${props.classNames ?? ''}`}>
Propably a leftover from the original code. 
Has been changed to a `div` now.

2023-06-07 08:27 UTC, andr9528 commented on src/client/components/thumbnail/thumbnail-overlay/thumbnail-overlay.tsx
> +  classNames?: string
I think i get what you mean, but i am unsure what change to make to fix this.

2023-06-07 08:34 UTC, andr9528 commented on src/client/components/thumbnail/thumbnail-picture/thumbnail-picture.scss
> +.thumbnail-picture {
Has been renamed to `ThumbnailImage`.

Originally 'Picture' was used, as it would otherwise the name would conflict with another component. That component is now called `ImageMediaCard`, and thus doesn't conflict any longer.

2023-06-07 08:42 UTC, andr9528 commented on src/client/components/thumbnail/thumbnail-picture/thumbnail-picture.tsx
> +export default function ThumbnailPicture(props: ThumbnailPictureProps): JSX.Element {
Have removed it by moving the code to the only place it was used.

Was originally made to better support single responsibility.

2023-06-07 08:50 UTC, andr9528 commented on src/client/components/thumbnail/thumbnails/thumbnails.tsx
> +export function Thumbnails(): JSX.Element {
Have been renamed to the suggested name.

2023-06-07 08:59 UTC, andr9528 commented on src/client/components/thumbnail/thumbnails/thumbnails.tsx
> +        : files
Not sure how much help that is...

``` typescript
function getShownFiles(files: MediaFile[], isInEditVisibilityMode: boolean, hiddenFiles: Record<string, HiddenFileInfo>): MediaFile[] {
    return  !isInEditVisibilityMode || browserService.isTextView()
        ? files.filter(({ name }) => !(name in hiddenFiles)) 
        : files
}
```

The values still need to be gotten from the `useSelectors`, as they cause the component to re-render if they are changed, which we want.

2023-06-07 09:38 UTC, andr9528 commented on src/client/components/thumbnail/thumbnails/thumbnails.tsx
> +        <div className="thumbnails-region">
Done.

2023-06-07 09:41 UTC, andr9528 commented on src/client/index.tsx
> +console.log('Redux initialized :', state)
Cliptool already includes TV2's logger, but it hasn't been implemented for the frontend - yet. 
It is planned to do so during UT-221.

2023-06-07 09:49 UTC, andr9528 commented on src/client/services/client-handler-service.ts
> +class ClientHandlerService {
If `Service` is removed from the name, is its home still in the `/services/` folder?

~Have renamed it to `BackendService`. Not adding `Api`, as no calls are done via this class.~

Has been renamed again following other comments.

2023-06-07 09:50 UTC, andr9528 commented on src/client/services/browser-service.ts
> +class BrowserService {
Explain plz.

2023-06-07 09:56 UTC, andr9528 commented on src/client/services/event-service.ts
> +// TODO: Come up with a better name.
It was used as a central place for how values was extracted from inputs on change. 
Have chosen to remove it, and just extract the value directly where it was used.

2023-06-07 10:30 UTC, andr9528 commented on src/client/services/socket-service.ts
> +class SocketService {
Have reworked it following close to the suggestions.

Classes that interact with the socket connection is as follows. Hopefully the names are detailed enough that i don't need to explain their content in detail.

- SocketService
  - Only creates socket and exposes it via a get method.
- BackendObserver
- BackendOperationApi
- BackendPlayApi
- BackendSettingsApi

2023-06-07 10:38 UTC, andr9528 commented on src/model/reducers/app-navigation-action.ts
> +        tabIndex: tabIndex,
I know it works, as i have seen Anders use it a couble of times. 
I however am not sure what is best for readability. 
Personally i like it as it is currently.

2023-06-07 10:38 UTC, andr9528 commented on src/model/reducers/app-navigation-action.ts
> +        isConnected: isConnected,
See commnet on https://github.com/tv2/casparcg-cliptool/pull/81#discussion_r1211562414

2023-06-07 11:44 UTC, andr9528 commented on src/model/reducers/media-models.ts
Renamed Model layer to shared, and then created new actions and models folders. Then i moved the actions and models folder into those folders. 

Please don't make me do something similar again... had to upade most refenreces by hand, as my VS Code was unable to perform a rename...

2023-06-07 11:48 UTC, andr9528 commented on src/model/reducers/media-reducer.ts
> +    })
Did you miss the point where the object shown is the default structure of a new output, that then afterwards gets filled with inputs from redux? Of cource the defaults all have the same structure...

2023-06-07 11:49 UTC, andr9528 commented on src/model/reducers/settings-models.ts
> +export interface CcgConfig {
Have renamed them to use the full name.

2023-06-07 11:55 UTC, andr9528 commented on src/model/schemas/old-settings-schema.ts
> +            arrayService.fillWithDefault(transform, false)
If you already had 3 elements, and then want to fill in default elements until e.g 8 exist, would the suggested way work?

2023-06-07 13:34 UTC, andr9528 commented on src/model/services/media-service.ts
> +            (predicate) => predicate.name === cleanFileName
Done.

2023-06-07 13:36 UTC, andr9528 commented on src/model/services/media-service.ts
> +class MediaService {
Because i make use of singleton pattern. If it was exported and then accessed, then none of the methods would be accessible before creating an instance. By making a single object, and exporting that methods become accesible.

2023-06-08 06:31 UTC, andr9528 commented on src/model/services/os-service.ts
> +    getThisMachineIpAddresses(): string[] {
Technically it was me who named it, when i merged 3 different locations that had this methods code.

Has been renamed to the suggested now.

2023-06-08 06:35 UTC, andr9528 commented on src/model/services/os-service.ts
> +class OsService {
https://en.wikipedia.org/wiki/Operating_system
You might know it :P

Not sure what else this service could be called. 
Was my idea to keep methods that gather infomation about the PC it is run on, e.g the IP, in this service.

2023-06-08 06:43 UTC, andr9528 commented on src/model/services/reducer-service.ts
> +class ReducerService {
It was meant as a service that the reducer would share some utility code on, however i couldn't get the function i wanted to share to work accros diffferent reducers to work.

Have moved the one function to its rightful place by where it is used, and deleted the service.

2023-06-08 06:44 UTC, andr9528 commented on src/model/services/settings-service.ts
> +            outputSettings: Array(8).fill(defaultOutputSettingsState),
Have added so it copies the object, via spread operator.

2023-06-08 10:40 UTC, andr9528 commented on src/model/services/array-service.ts
> +            array.push(defaultValue)
Have changed it so incase it is an array or object, the spread oerator is used to create a copy instead.

2023-06-12 06:53 UTC, andr9528 commented on src/model/services/time-service.ts
> +        durations: [number, number] = [0, 0],
Has now been renamed.

2023-06-12 07:03 UTC, andr9528 commented on src/model/services/time-service.ts
> +        }
Have moved client related code to a new 'ClientTimeService' that wraps the current methods.

2023-06-12 07:04 UTC, andr9528 commented on src/model/services/time-service.ts
> +        const time = Math.max(0, durations[1] - durations[0])
Done

2023-06-12 07:04 UTC, andr9528 commented on src/model/services/time-service.ts
> +    private leadingZero(num: number, length: number = 2): string {
Done

2023-06-12 07:05 UTC, andr9528 commented on src/model/services/time-service.ts
> +    public durationToTimeCode(
Done

2023-06-12 07:07 UTC, andr9528 commented on src/model/services/time-service.ts
> +class TimeService {
Because of the use of singleton pattern.

When DI is added as part of UT-221, all or most of the services are going to be changed to export, and then be retrieved via DI.

2023-06-12 07:09 UTC, andr9528 commented on src/model/socket-io-constants.ts
> +export enum ServerToClient {
Have suffixed `Command` to both.

2023-06-12 07:20 UTC, andr9528 commented on src/model/socket-io-constants.ts
> +    THUMBNAIL_UPDATE = 'thumbUpdate',
Values updated to use lowercase kebab-casing and fixed the few that didn't match their constant representation.

2023-06-12 07:27 UTC, andr9528 commented on src/server/index.ts
> +process.on('unhandledRejection', (error) => processUnhandledRejection(error))
As the called function only logs the error and then re-throws, does it hurt if it stays?
Don't know how the stacktrace gets effected by this in Typescript. In C#, in a catch clause you would just write `throw` after you have done what you can to recover/log, and it would then throw the original exception, without altering the stacktrace.

It would make it easier to potentially track down a future unhandled rejection crash/error that may or may not happen.

2023-06-12 07:49 UTC, andr9528 commented on src/server/services/hidden-files-persistence-service.ts
> +                this.validateHiddenFiles(hiddenFilesFromFile)
Renamed function to `invalidateHiddenFiles`, as a `true` return, means that the hidden files contains one or more invalid entries.

2023-06-12 07:50 UTC, andr9528 commented on src/server/services/hidden-files-persistence-service.ts
> +            const hiddenFilesFromFile: Record<string, HiddenFileInfo> =
Done

2023-06-12 07:51 UTC, andr9528 commented on src/server/services/hidden-files-persistence-service.ts
> +class HiddenFilesPersistenceService {
See Response: https://github.com/tv2/casparcg-cliptool/pull/81#discussion_r1226180695

2023-06-12 07:56 UTC, andr9528 commented on src/server/services/hidden-files-persistence-service.ts
> +            if (isInvalidHiddenFiles) {
Would creating a new constant as follows help?
```typescript
const wasInvalidHiddenFiles = isInvalidHiddenFiles
if (wasInvalidHiddenFiles ) {
    this.save()
}
```

The save functions takes whats going to be saved from the redux state, which just prior to this `if` statement has been updated with the new cleaned record. Not sure if anything should be done...

2023-06-12 08:47 UTC, andr9528 commented on src/server/services/hidden-files-persistence-service.ts
> +                    'File containing hidden files not found, or not yet stored.'
Load function has had its body reworked to make the two path for clear, ultimately also improving the logged information.

2023-06-12 08:48 UTC, andr9528 commented on src/server/services/hidden-files-persistence-service.ts
> +            if (isInvalidHiddenFiles) {
Might not need any additional changes due to changes made for: https://github.com/tv2/casparcg-cliptool/pull/81#discussion_r1211752874.

2023-06-12 09:11 UTC, andr9528 commented on src/server/services/hidden-files-persistence-service.ts
> +            this.getCleanHiddenFiles(hiddenFiles)
I believe i did consider that, and had some reason for it when creating it.

Looking at its usage at the moment, it does appear that i could take in the hidden files as an arguement, and no additional work will be needed at usage sites, other than passing on the value.

Will/have change(d) it to take in the hidden files to save as an arguement.

2023-06-12 09:23 UTC, andr9528 commented on src/server/services/hidden-files-persistence-service.ts
> +        persistenceService.saveFile(
What you mean?

The Logging is done via a callback yes, as the `fs` library used to write the file has a callback when completed, good or bad.
Writing the file is done asynchronous, which is done via callback with `fs`, as it doesn't appear to support promise based asynchronous...

2023-06-12 09:28 UTC, andr9528 commented on src/server/services/hidden-files-persistence-service.ts
> +            (error: any) => {
`fs` is imported via a require statement. 
It is from this one that the callback comes, and i am not sure what type it has, as `fs` is displayed as an `any`...

Would very much like it to not be an `any`, just not sure how to figure out the correct type to apply...

2023-06-12 09:30 UTC, andr9528 commented on src/server/services/hidden-files-persistence-service.ts
> +            this.validateHiddenFiles(originalHiddenFiles)
One call to the now named `invalidateHiddenFiles` has been eliminated with some reworking of the Load function.
Not sure if that is sufficent?

2023-06-12 09:33 UTC, andr9528 commented on src/server/services/hidden-files-persistence-service.ts
> +    private validateHiddenFiles(
hmm, now that you mention that name, that does seem better than `invalidateHiddenFiles`.
Have renamed it to the suggested name.

2023-06-12 09:34 UTC, andr9528 commented on src/server/services/hidden-files-persistence-service.ts
> +    private clearInvalidHiddenFiles(
Name suggestion applied.

2023-06-12 09:35 UTC, andr9528 commented on src/server/services/persistence-service.ts
> +class PersistanceService {
See response: https://github.com/tv2/casparcg-cliptool/pull/81#discussion_r1226180695

2023-06-12 09:46 UTC, andr9528 commented on src/server/services/persistence-service.ts
> +const path = require('path')
Those are the original packet used to save/read file from drive.
I am not entirely sure which packages they correspond to on NPM,

Would very much like for them to be imported instead of required.
While trying to find the `fs` package on NPM, i found this one: https://www.npmjs.com/package/jsonfile
Perhabs the persistance logic could/should be updated to use that one instead.
Would also allow for promise based operations, instead of callback.

2023-06-12 09:48 UTC, andr9528 commented on src/server/services/persistence-service.ts
> +        file: string,
Ahh, riiight. Have renamed `file` to `fileContent`.

2023-06-12 09:52 UTC, andr9528 commented on src/server/services/persistence-service.ts
> +        if (!fs.existsSync('storage')) {
Would like to, just not entirely sure how...
Will propably help when other `fs` related comments are addressed during a chat.

2023-06-12 09:53 UTC, andr9528 commented on src/server/services/settings-persistence-service.ts
> +class SettingsPersistenceService {
See response: https://github.com/tv2/casparcg-cliptool/pull/81#discussion_r1226180695

2023-06-12 09:55 UTC, andr9528 commented on src/server/services/settings-persistence-service.ts
> +            const isOld = this.isPreviousStructure(settingsFromFile)
Have suffixed `Structure` onto it. Same for the `isNew` constant just below.

2023-06-12 10:52 UTC, andr9528 commented on src/server/services/settings-persistence-service.ts
> +    private isPreviousStructure(loadedFile: any): {
Renamed argument to `rawSettings`.

2023-06-12 11:25 UTC, andr9528 commented on src/server/services/settings-persistence-service.ts
> +            const isOld = this.isPreviousStructure(settingsFromFile)
Have broken up the Load method similar to how has been suggested.
I do however, with the current setup, need to check if the structure is the old one first, as getting the new one, should/does not fail, as it simply fills it out with defaults, if value are missing.

A chat about how that could/should be changed to allow the new structure to be checked first would be nice.

2023-06-14 07:18 UTC, andr9528 commented on src/client/services/browser-service.ts
> +}
Asked Kasper about this, and it sounded like it was a feature that was used every so often.

Thankfully it turns out to be really easy to support for this - easier than i first thought.
As can propably be guessed from the previous statement, i have added the functionality needed for Channel and Textview to be enabled together.

2023-06-14 07:43 UTC, andr9528 commented on src/server/services/hidden-files-persistence-service.ts
> +    private validateHiddenFiles(
`invalidateHiddenFiles` has been renamed to `hasSelectedOrCuedHiddenFiles`, and expanded to also check for if the value is cued.

2023-06-19 08:47 UTC, LindvedKrvang commented on src/client/components/footer/operation-mode-footer.tsx
> +export function OperationModeFooter(): JSX.Element {
> Say 1-∞ more operation modes are added.
Would you want the logic to decide which to show to be in the parent? or tucked away neatly in this component?

Each of these modes is basically its own flow/feature. As we talked about, you would just make a component that encapsulate each flow/feature and that component would have/not have whichever components it needs to render.

This is the exact same logic for including/not including the header in different pages.

> This component was originally build together with Anders, so it can't be all bad, right?

I think you would be surprised to learn how often we write bad stuff that we then go and refactor once we get smarter/learn a new detail we didn't know before. The reason you may not see this is because we dont' hesitate refactor/delete our own code when we learn our solution is not sufficient enough.

2023-06-19 12:22 UTC, LindvedKrvang requested changes
There is a lot of things that needs to be addressed that I skipped for the sake of getting this PR merged.

There are however some things that must be addressed. I have commented many of them, but I need to emphasize two things:

The first thing, and by far the worst one: Your usage of singletons.
For some reason you have made an abundance of the classes singletons. I counted _one_ place where a singleton _might_ be suitable. Only _one_ place.

A singleton is used to ensure that all consumers of a class calls the same data/state. This is not a need you have in almost all of your classses. Besides, this project used Redux which accomplies the same thing, so one more reason not to use singletons.

Many of the classes you have made singletons are "utility" classes. I.e. classes that just need an input and then provides an output. Classes that don't care about state at all. Since singletons is for classes that cares about state, then these "utility" classes should not be singletons.

What's even worse is that you call the instance method of your singletons over and over again in the classes that you use them in. This is no better than just making each method static and call the static method (especially because your classes allready don't care about state).

The second thing I need to address is the folder structure. It seems like you are on the right track, but haven't fully understood how it should be.

As we talked about, we want to separate our folders by feature/pages. That means that the folder structure should look like this:
```
-src/
  -featureX/
    -components/
      -componentA/
      -componentB/
    -services/
  -featureY/
    -components/
      -componentC/
      -componentD/
    -services/
      -someService/
      -someOtherService/
  -shared/
    -components/
      -componentE/
      -componentF/
    -services/
```
What this would like in this project would be something like this:
```
-src/
  -frontPage/
    -components/
      -FrontPageComponent
      ...
  -settings/
    -components/
      -SettingsPageComponent
      ...
  -shared/
    -components/
      -HeaderComponent
      -FooterComponent
```

2023-06-19 12:22 UTC, LindvedKrvang commented on src/client/components/header/application-header/application-header.tsx
> +export default function ApplicationHeader(): JSX.Element {
Just call it `Header`. What information do `Application` give that is not allready in `Header`?

2023-06-19 12:22 UTC, LindvedKrvang commented on src/client/components/media-card/image-media-card/image-media-card.tsx
> +    <div className={`c-image-media-card ${isHidden ? 'hidden' : ''}`}>
Why do you need a CSS class to hide the component? You could just not render it if it shouldn't be show:
```
return (
  {!isHidden && (
    <div>...</div>
  )}
)
```

2023-06-19 12:22 UTC, LindvedKrvang commented on src/client/components/media-card/image-media-card/image-media-card.tsx
> +    <div className={`c-image-media-card ${isHidden ? 'hidden' : ''}`}>
But this is also ties into the discussion: "It's weird that you render a component that then decides not to render itself." It should be the calling component that figures out if it should render its child components or not.

2023-06-19 12:22 UTC, LindvedKrvang commented on src/client/services/backend-observer.ts
> +export class BackendObserver {
Why is this called `Backend`? It's a service that lives in the frontend so it shouldn't be named "Backend" (it also should not be named "Frontend").

What does it observe?

2023-06-19 12:22 UTC, LindvedKrvang commented on src/client/services/backend-observer.ts
> +        console.log('BackendObserver: Monitoring messages from socket...')
This message indicated that a more apt name for this class would be `SocketObserver`

2023-06-19 12:22 UTC, LindvedKrvang commented on src/client/services/backend-play-api.ts
> +export class BackendPlayApi {
You should not be naming your files in the frontend `BackendX`. (goes for all files that you have named `backend`)
Instead you should have a form of service that does what you want.
In this case `BackendPlayApi` would be more aptly named `PlayService`.

First of, this is not the backend. The file tries to call something _on_ the backend, but that just not justify calling this `backend`.
What if you don't need to call the backend at all in order to play files? Then you would have to rename your class.
It's an implementation detail whether or not this class calls the backend and we don't expose implementation details.

Second: This is not an API, so it shouldn't be called `Api`.

2023-06-19 12:22 UTC, LindvedKrvang commented on src/client/services/backend-play-api.ts
> +    public emitPlayFile(outputIndex: number, fileName: string) {
`emit` is an implementation detail of how this class has decided to connect to a server. We don't want to reveal implementation details. This method plays a file when called, then simply call it `playFile`.

To illustrate a bit better why you don't want to include implementation details; say we have:
```typescript
interface PlayService {
  playFile: void
}

class SocketPlayService implements PlayService {
  const socket: Socket = new Socket()

  playFile(): void {
    this.socket.emit()
  }
}

class HttpPlayService implements PlayService {
  const http: Http = new Http()

  playFile(): void {
    this.http.put(...) // or whatever http call is used
  }
}
```
Since we did not include any implementation details in our method names, we are able to substitute with any implementation and they all comply with the interface.

If we instead had the interface:
```typescript
inteface PlayService {
  emitPlayFile(): void
}
```
We would all of a sudden have a Http implementation that is forced to used Socket semantics.
```typescript
new HttpPlayService().emitPlayFile()
```

2023-06-19 12:22 UTC, LindvedKrvang commented on src/client/services/backend-play-api.ts
> +    static readonly instance = new BackendPlayApi(
Why is this a singleton?
I get that you want to reuse the Socket connection, but you are allready using a singleton for the Socket, so there is absolutely no need for this also being a singleton (this applies to basically all the singletons you made).

Also, when you make a singleton you _must_ make the constructor private as well.
There is currently nothing stopping me from writing `new BackendPlayApi(SocketService.instance.getSocket())` and completely bypass your singleton.

2023-06-19 12:22 UTC, LindvedKrvang commented on src/server/index.ts
> +process.on('unhandledRejection', (error) => processUnhandledRejection(error))
As it is code made for testing it most definately should not end up in production.

> It would make it easier to potentially track down a future unhandled rejection crash/error that may or may not happen.

YAGNI

2023-06-19 12:22 UTC, LindvedKrvang commented on src/server/services/hidden-files-persistence-service.ts
> +        PersistenceService.instance
You should not be calling you singletons instance methods every single time you need them. This is a very bad practice and this is basically the same as you just making all the methods on the class static.
How are you going to mock away the dependency in a unit test?
How are you going to provide a different implementation without having to change everywhere you use it?

2023-06-19 12:22 UTC, LindvedKrvang commented on src/server/services/persistence-service.ts
> +export class PersistenceService {
This class is reading and writing to files. There is no state saved in the class. There is no need for this class to be a singleton.

2023-06-19 12:22 UTC, LindvedKrvang commented on src/shared/services/array-service.ts
> +    fillWithDefault<T>(
This class is completely redundant. The class does one thing and that one thing is allready provided by default in Typescript as `Array.fill()`.

This class should be deleted.

Also, you made it a singleton. Singleton should only be used when you want to ensure all consumers accesses the same data/state. This is a utility service, so there is neither class/nor state in here, so this should not be a singleton.

2023-07-03 06:40 UTC, andr9528 commented on src/client/components/header/application-header/application-header.tsx
> +export default function ApplicationHeader(): JSX.Element {
Renamed it back to `Header`. Can't fully remember why `Application` was added, just that it was Anders who suggested it during our talk about a number of comments.

2023-07-03 06:45 UTC, andr9528 commented on src/client/components/media-card/image-media-card/image-media-card.tsx
> +    <div className={`c-image-media-card ${isHidden ? 'hidden' : ''}`}>
`hidden` is this case applies some css to indicate that the card in question is hidden, while not Editting Visibility of cards. For this PR, it is only some sizing, but already in #84 / UT-216 this is expanded to add more css styling.

Maybe the constant needs a better name, just not sure what...

2023-07-03 06:49 UTC, andr9528 commented on src/client/services/backend-observer.ts
> +export class BackendObserver {
It observers, or maybe a better word listens, for event from the backend.

The new name was created following 1 or more comments made during the long PR review. You might have left before they left that/those comment(s) though...

2023-07-03 06:53 UTC, andr9528 commented on src/client/services/backend-observer.ts
> +        console.log('BackendObserver: Monitoring messages from socket...')
The class makes use of a socket for the communication **at the moment**, which does support your comment, but it is also a implementation detail, which afaik should not be part of the name.

2023-07-03 06:59 UTC, andr9528 commented on src/client/services/backend-play-api.ts
> +    public emitPlayFile(outputIndex: number, fileName: string) {
This one is on me, when moving the methods to the services, i forgot it update the names to removed the `emit` part. Has been done now.

2023-07-03 07:03 UTC, andr9528 commented on src/client/services/backend-play-api.ts
> +export class BackendPlayApi {
I get what is being said, and will gladly make that change, but i would like a talk about it together with Anders too, as the names was sorta his suggestion, and also matches with how the domain communication/naming should be when UT-203 is eventually done.

2023-07-03 07:08 UTC, andr9528 commented on src/server/services/hidden-files-persistence-service.ts
> +        PersistenceService.instance
UT-221 exists to specifically address this.

2023-07-04 10:53 UTC, andr9528 commented on src/shared/services/array-service.ts
> +    fillWithDefault<T>(
First, it is no longer a singleton.

Secondly, does the `Array.fill()` work to fill up an existing array with more/new values?
Say you have an array with 3 numbers (eg. 1, 2 and 3) and then wants to fill in more numbers up to 8, with some default, does it work for that?
From what i can tell `Array.fill()` will not expand an array when used on an existing array, it will only overwrite existing slots.

2023-07-04 11:53 UTC, andr9528 commented on src/server/services/hidden-files-persistence-service.ts
> +        PersistenceService.instance
All but one service is no longer singleton.

2023-07-04 11:54 UTC, andr9528 commented on src/server/services/persistence-service.ts
> +export class PersistenceService {
No longer a singleton.

2023-07-11 09:53 UTC, andr9528 commented on src/client/services/backend-play-api.ts
> +    static readonly instance = new BackendPlayApi(
All but one service have been made not singleton.

2023-07-11 12:15 UTC, KvelaGorrrrnio approved these changes
I approve under the assumption that the comments I have provided are addressed.
Some of them might be outdated, in which case you can just ignore them. I had some comments I made some time ago, that I forgot to commit – sorry about that :/

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on .gitignore
> +/src/.vs
This might just be a personal opinion, but generally speaking, unless explicitly agreed on, config files for editors should not be part of the revisioned files nor the repos gitignore. Instead a global gitignore should be defined e.g. in your home directory with the rules that are necessary for your setup.

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/components/application-router/application-router.tsx
> +        (state: State) => state.appNavigation.isConnected)
A general note. When we have a opening bracket of some sort, followed by a newline, the closing bracket should match the scope of the opening bracket – if the contents cannot be placed on the same line.
So this should either be:
```typescript
    const isConnected: boolean = useSelector((state: State) => state.appNavigation.isConnected)
```
or
```typescript
    const isConnected: boolean = useSelector(
        (state: State) => state.appNavigation.isConnected
    )
```

It might just be a linting rule that needs to be changed.

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/components/header/application-header/application-header.tsx
> +export default function ApplicationHeader(): JSX.Element {
@LindvedKrvang Personally I think `Header` is too generic. I would expect some sort of generic `header` element if the component is called `Header`. `Application` might not be the best fit, but then we could have a look at what kind of header this is and give it an appropriate name. Since the primary focus of the header is to display information about what media is playing and how it is played, then perhaps `MediaHeader`, `MediaPlayerHeader` or `MediaControlHeader`? Other suggestions are welcomed :grin:

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/components/header/timer-thumbnail/timer-thumbnail.scss
> +.c-timer-thumbnail-timer {
To indicate that the last `timer` part is a sub component of the `.c-timer-thumbnail` component, you should per BEMIT use `__`, such that the class becomes `.c-timer-thumbnail__timer`.
The same goes for the `.c-timer-thumbnail-thumbnail`.

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/components/media-card/card-overlay-display/card-overlay-display.scss
> +.c-card-overlay-display {
The class names are inconsistent. Sometimes `card` is used as a prefix and at other times it is used as a suffix. This should be consistent.

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/components/media-card/card-overlay/card-overlay.tsx
> +  }
What is the purpose of this switch statement? It seems redundant.

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/components/media-card/file-name-display/file-name-display.tsx
> +        .slice(-45)
Why this magic `-45`?

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/components/media-card/image-media-card/image-media-card.scss
> +.c-image-media-card__image {
This should be defined under the `.c-image-media-card` selector as `&__image`.

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/components/media-card/card-overlay-display/card-overlay-display.tsx
> +export default function CardOverlayDisplay(props: CardOverlayDisplayProps): JSX.Element {
What does `Display` indicate in this scenario?

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/components/media-card/card-overlay-display/card-overlay-display.tsx
> +  )
Why is there a `SelectedCardOverlay` but not a `CuedCardOverlay`? They seem to both use the `CardOverlay` with the `showAs` property.

Another thing is that `CardOverlay` sounds like an overlay over a card. Should it be `OverlayCard`? And what is the difference between an overlay and a card overlay/ overlay card?

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/components/media-card/media-card/media-card.tsx
> +      <div
A button should not be a div – it should be a button.

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/components/media-card/selected-card-overlay.tsx
> +  time: [number, number]
This is a time range, not time.

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/components/settings/casparcg-settings/casparcg-settings.tsx
> +    const transitionTime = props.casparcgSettings.transitionTime
Just a note for future code, when you have multiple values that you want extracted from the same object (or array), you can use destructuring. Then this becomes:
```typescript
    const  { ip, amcpPort, oscPort, defaultLayer, transitionTime } = props.casparcgSettings
```

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/components/settings/output/output.tsx
> +  configChannel: CaspercgConfigChannel
CasparCG is misspelled here. There are no `e` in the name :D

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/components/settings/output/output.tsx
> +    const scaleY = props.outputSettings.scaleY
Desctructuring can be used here as well – if the temporary variables are needed.

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/components/settings/settings-actions/settings-actions.scss
> +.c-settings-actions-button {
`-actions` can be removed.

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/components/settings/settings-actions/settings-actions.tsx
> +  const buttonCss = "c-settings-actions-button"
This string does not contain CSS. It contains a CSS class name.
But more importantly, this should be made its own component. That way you don't need to store the css class name as a variable and reference it in multiple places.

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/components/settings/settings-page/settings-page.tsx
> +    function onCasparcgChanged(changedCasparcg: CasparcgSettings): void {
Does this refer to when CasparCG settings are changed? If so, this should be made explicit. The same goes for `onOutputsChanged`.

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/components/shared/checkbox/checkbox.scss
> +}
We are using SCSS. The `__input` should be defined under the `.c-checkbox` selector as `&__input`.

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/components/shared/checkbox/checkbox.tsx
> +export default function Checkbox(props: CheckboxProps): JSX.Element {
Would be nice if we don't use default exports.

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/components/shared/swipeable.tsx
> +  function isValidChild(child: number, childCount: number): boolean {
You are not checking if there is a valid child, you are checking if it is a valid index.

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/components/shared/switch/switch.tsx
> +    className={`${props.className ?? 'c-switch'} ${props.checked ? 'on' : ''}`}
In what scenario would you overwrite the class to something else than `c-switch`?

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/components/tab/tab/tab.tsx
> +      <MediaOverview/>
This is not a tab. It is a tab holding the media overview. Is this component necessary?

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/components/tab/tabs/tabs.tsx
> +        <div className='tabs-bar__tab-titles'>
Is `tab-` necessary?

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/services/backend-observer.ts
> +        oldtime: [number, number],
This is a time range. And perhaps we should make a type alias for it to make it more explicit.

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/main-page/components/media-card/media-card.tsx
> +    || new ReduxSettingsService().isCardCuedOnAnyOutput(fileName, state.settings)) {
In this case it would make sense to store the ReduxSettingsService instance in a local variable, since it might be used multiple times.

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/main-page/components/timer-thumbnail/timer-thumbnail.tsx
> +        || new ReduxSettingsService().getCleanCuedFileName(settingsOutput, state.settings)
It makes sense to store the ReduxSettingsService in a local variable, since it might get used multiple times in this scope.

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/settings-page/components/number-input/number-input.tsx
> +import '../shared.scss'
Why is the file called shared.scss?

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/settings-page/components/settings-actions/settings-actions.scss
> +.c-settings-actions-button {
Wouldn't `.c-settings-button` suffice?

2023-07-11 12:15 UTC, KvelaGorrrrnio commented on src/client/settings-page/components/text-input/text-input.scss
> +  border-style: solid;
`.c-text-input__input` should be nested under `.c-text-input` as `&__input`.

2023-07-11 13:04 UTC, andr9528 commented on src/client/components/application-router/application-router.tsx
> +        (state: State) => state.appNavigation.isConnected)
I have fixed it manually in a number of places. 
Unsure if styling being applied on commit will undo any/all of that...

2023-07-11 13:06 UTC, andr9528 commented on .gitignore
> +/src/.vs
I think i get what you are saying, but i am not sure how to set it up.

2023-07-11 13:33 UTC, andr9528 commented on src/client/components/header/application-header/application-header.tsx
> +export default function ApplicationHeader(): JSX.Element {
After Anders late comment, i broke the Header appart such that:
1.Tthe header parts that should always be there are in a `Header` component under shared.
2. A more specific version exist under `main-page` called `MediaControlHeader`, which build upon the base and adds whats needed for a header specific to `main-page`.

Hope this satifies both parties.

2023-07-11 13:36 UTC, andr9528 commented on src/client/components/header/timer-thumbnail/timer-thumbnail.scss
> +.c-timer-thumbnail-timer {
Done that now.

2023-07-11 13:37 UTC, andr9528 commented on src/client/components/header/timer-thumbnail/timer-thumbnail.scss
> +.c-timer-thumbnail-timer {
Propably other components where that needs to be done, and i am doing it ever so slowly, when i notice a scss thats missing it.

2023-07-12 09:40 UTC, andr9528 commented on src/client/settings-page/components/text-input/text-input.scss
> +  border-style: solid;
Done that for this, and the number/checkbox inputs too.

2023-07-12 09:45 UTC, andr9528 commented on src/client/settings-page/components/settings-actions/settings-actions.scss
> +.c-settings-actions-button {
It would, but i was trying to use BEMIT, which i did poorly.

There is now a css class for the component we are in (`.c-settings-actions`) and in that a `&__button` with the css being applied.

2023-07-12 10:03 UTC, andr9528 commented on src/client/settings-page/components/number-input/number-input.tsx
> +import '../shared.scss'
Because the css defined in it is shared between a handful of the different settings page components.
Not sure what other name might fit better.

2023-07-12 10:07 UTC, andr9528 commented on src/client/main-page/components/timer-thumbnail/timer-thumbnail.tsx
> +        || new ReduxSettingsService().getCleanCuedFileName(settingsOutput, state.settings)
On one hand yes to reduce how many times it gets created.
But on the other hand no, cause then it will hardly ever get gc'ed, which was one of the reason for it not being singleton.

2023-07-12 10:10 UTC, andr9528 commented on src/client/main-page/components/media-card/media-card.tsx
> +    || new ReduxSettingsService().isCardCuedOnAnyOutput(fileName, state.settings)) {
Same resonse as this: https://github.com/tv2/casparcg-cliptool/pull/81#discussion_r1260941983

2023-07-12 10:10 UTC, KvelaGorrrrnio commented on src/client/main-page/components/timer-thumbnail/timer-thumbnail.tsx
> +        || new ReduxSettingsService().getCleanCuedFileName(settingsOutput, state.settings)
If you instantiate it as a local variable, then at the end of the scope, the variable along with the instance should be collected :)

2023-07-12 10:12 UTC, KvelaGorrrrnio commented on .gitignore
> +/src/.vs
There is a tutorial for it here: https://medium.com/self-modifying-code/create-a-global-gitignore-step-by-step-for-macos-and-windows-31a765291409

2023-07-12 10:15 UTC, KvelaGorrrrnio commented on src/client/settings-page/components/number-input/number-input.tsx
> +import '../shared.scss'
Calling it shared and having multiple different parts defined in here invites for other unrelated stuff to crawl in. In my opinion it could be split. I can see that a dedicated file for input styling was removed and the contents moved to shared.scss.

 I will leave it be for this PR, but it would be nice at some point to have the CSS properly organized :)

2023-07-12 10:16 UTC, KvelaGorrrrnio commented on src/client/settings-page/components/settings-actions/settings-actions.scss
> +.c-settings-actions-button {
Let us drop the CSS structure and stuff for this PR. We can have a look at it at some other time.

2023-07-12 10:32 UTC, andr9528 commented on src/client/components/media-card/card-overlay/card-overlay.tsx
> +  }
It inded is redundant, but only because the string text in the enum values matches the css classes.
Have removed the switch.

2023-07-12 10:49 UTC, andr9528 commented on src/client/components/media-card/card-overlay-display/card-overlay-display.scss
> +.c-card-overlay-display {
So we have the actual cards using `card` as suffix (`image-media-card`, `text-media-card` & `media-card`). Last of those is the base component used by the other two.

Then we have the ones that use `card` as prefix (`card-overlay`, `card-overlay-display`, and kinda `selected-card-overlay`).
`card-overlay` and `selected-card-overlay` are displayed by `card-overlay-display` when the correct conditions are met.

`card-overlay-display` are displayed on `image-media-card` and `text-media-card`.

When used as a prefix, it it to indicate that they are to be used one af `card`. Whereas when used as a suffix, it is to define the components as a card.

Not sure if the names still needs to change, and if so, to what...

2023-07-12 10:52 UTC, andr9528 commented on src/client/components/media-card/file-name-display/file-name-display.tsx
> +        .slice(-45)
That slicing was there originally, and i think it stems from how CasparCG formats the filename that Cliptool receives.

2023-07-12 10:55 UTC, andr9528 commented on src/client/components/media-card/image-media-card/image-media-card.scss
> +.c-image-media-card__image {
Done that. Also fixed similar mistake for `text-media-card`.

2023-07-12 10:58 UTC, andr9528 commented on src/client/components/media-card/card-overlay-display/card-overlay-display.tsx
> +export default function CardOverlayDisplay(props: CardOverlayDisplayProps): JSX.Element {
Hmm. This component choses which `card-overlay` to show, if any, and displays it.

It could maybe benefit from at better name...

2023-07-12 11:06 UTC, andr9528 commented on src/client/components/media-card/card-overlay-display/card-overlay-display.tsx
> +  )
1.
There is a `SelectedCardOverlay`, due to it having a handful of extra logic needed for transfomring the saved duration to the displayed duration.

On the other hand Cued only ever displays a static text, thus seemed overkill to create a full on component for that.

2.
`CardOverlay` sounds and is an overlay over a card.
A `OverlayCard` would be a full blown card making use `media-card` as its base, having a similar setup as `ìmage-media-card` or `text-media-card`. Not sure where such a card would be used.

2023-07-12 11:13 UTC, andr9528 commented on src/client/components/media-card/media-card/media-card.tsx
> +      <div
I am up for changing it, BUT i'd need a hand to nullify much of the default css that button has, which we do not want.

This is how it looks, with the div as a button instead:
![image](https://github.com/tv2/casparcg-cliptool/assets/21788044/7d128903-6e9f-4aa0-a961-ab9509eedde2)

But we want it to look like this:
![image](https://github.com/tv2/casparcg-cliptool/assets/21788044/7598cc81-2af9-479f-810f-e6c76d3d4526)

2023-07-12 11:14 UTC, andr9528 commented on src/client/components/media-card/selected-card-overlay.tsx
> +  time: [number, number]
Has been renamed.

2023-07-12 11:19 UTC, andr9528 commented on src/client/components/settings/casparcg-settings/casparcg-settings.tsx
> +    const transitionTime = props.casparcgSettings.transitionTime
Changed to use destructuring.

2023-07-12 11:21 UTC, andr9528 commented on src/client/components/settings/output/output.tsx
> +  configChannel: CaspercgConfigChannel
Fixed.

2023-07-12 11:22 UTC, andr9528 commented on src/client/components/settings/output/output.tsx
> +    const scaleY = props.outputSettings.scaleY
Has been updated to use desctructuring on all but one.
The last one needs some transformations, which is the only reason.

2023-07-12 11:26 UTC, andr9528 commented on src/client/components/settings/settings-actions/settings-actions.scss
> +.c-settings-actions-button {
You already commented on this :P
(https://github.com/tv2/casparcg-cliptool/pull/81#discussion_r1259628578)
And as you also commented, we are going to do a propper go over the css at another time.

2023-07-12 11:27 UTC, andr9528 commented on src/client/components/settings/settings-actions/settings-actions.tsx
> +  const buttonCss = "c-settings-actions-button"
Gone per similar comment by Lindved.

2023-07-12 11:28 UTC, andr9528 commented on src/client/components/settings/settings-page/settings-page.tsx
> +    function onCasparcgChanged(changedCasparcg: CasparcgSettings): void {
Added `Settings` to both functions names.

2023-07-12 11:28 UTC, andr9528 commented on src/client/components/shared/checkbox/checkbox.scss
> +}
Done that.

2023-07-12 11:36 UTC, andr9528 commented on src/client/components/shared/checkbox/checkbox.tsx
> +export default function Checkbox(props: CheckboxProps): JSX.Element {
From looking up standards for exporting components in react, this seems to be the way of doing it.

Even if we were to not follow this standard, i'm not changing that now, as it would require me to update the imports of all the components, which VS Code isn't happy about...

If you still want it changed, i will do it, in a seperate PR, at some later date.

2023-07-12 11:38 UTC, andr9528 commented on src/client/components/shared/swipeable.tsx
> +  function isValidChild(child: number, childCount: number): boolean {
Updated to use `index` instead of `child`.

2023-07-12 11:39 UTC, andr9528 commented on src/client/components/shared/switch/switch.tsx
> +    className={`${props.className ?? 'c-switch'} ${props.checked ? 'on' : ''}`}
Easy, you wouldn't, as that prop no longer exist.

2023-07-12 11:48 UTC, andr9528 commented on src/client/components/tab/tab/tab.tsx
> +      <MediaOverview/>
Moved what little this had, over to be applied at the only place used, which was `main-page`.

2023-07-12 11:51 UTC, andr9528 commented on src/client/components/tab/tabs/tabs.tsx
> +        <div className='tabs-bar__tab-titles'>
This is marked `Outdated`, and for good reasons, as i can't tell what you are refering to any longer. Hopefully what ever it was, has been fixed.

2023-07-12 11:55 UTC, andr9528 commented on src/client/services/backend-observer.ts
> +        oldtime: [number, number],
Updated the arguement name.

Also considered making the type alias, but i'd like to do that together with someone, so we can talk and agree on it, and only need to update all the references ones.

2023-07-12 13:49 UTC, andr9528 commented on .gitignore
> +/src/.vs
Fixed :D

2023-07-13 06:22 UTC, KvelaGorrrrnio commented on src/client/components/media-card/card-overlay/card-overlay.tsx
> +  }
But in that case you should not use the `CardOverlayType` enum as css class. You could instead use constant literals.

2023-07-13 06:23 UTC, KvelaGorrrrnio commented on src/client/components/media-card/file-name-display/file-name-display.tsx
> +        .slice(-45)
A suggestion could be to extract this to a constant.

2023-07-13 06:32 UTC, KvelaGorrrrnio commented on src/client/components/media-card/media-card/media-card.tsx
> +      <div
But is it only the image that should trigger an action, not the entire card?

2023-07-13 07:20 UTC, KvelaGorrrrnio commented on src/client/components/media-card/card-overlay/card-overlay.tsx
> +  }
I can see that the switch statement is removed from the file and uses `showAs: CardOverlayType`.
I encourage you to still have a switch statement for mapping the enum to the actual CSS classes. E.g.:
```typescript

function getCardOverlayCssClass(cardOverlayType: CardOverlayType): string {
  switch (cardOverlayType) {
    case CardOverlayType.CUED:
      return 'c-card-overlay--cued'
    case CardOverlayType.SELECTED:
      return 'c-card-overlay--selected'
    case CardOverlayType.NONE:
    default:
      return ''
}

2023-07-13 07:31 UTC, KvelaGorrrrnio commented on src/client/components/media-card/card-overlay-display/card-overlay-display.scss
> +.c-card-overlay-display {
The "card" flow seems a bit too complex. It will be a good candidate for a round 2 refactor at some later point :D

2023-07-13 07:35 UTC, KvelaGorrrrnio commented on src/client/components/media-card/card-overlay-display/card-overlay-display.tsx
> +export default function CardOverlayDisplay(props: CardOverlayDisplayProps): JSX.Element {
As I mentioned in another comment, the card flow could be revised. It seems to be a tad too complex :)

2023-07-13 07:36 UTC, KvelaGorrrrnio commented on src/client/services/backend-observer.ts
> +        oldtime: [number, number],
I suggest:
```typescript
// A time range consisting of a start time and end time.
type TimeRange = [number, number]
```

2023-07-13 10:14 UTC, andr9528 commented on src/client/components/media-card/card-overlay/card-overlay.tsx
> +  }
Applied your suggestion.
Will also better allow the the enum to have any key/value and still map to a meaningfull css classname.

2023-07-13 10:26 UTC, andr9528 commented on src/client/components/media-card/file-name-display/file-name-display.tsx
> +        .slice(-45)
After checking this abit more, it would appear that the `.slice(-45)`, is not needed.

2023-07-13 10:37 UTC, andr9528 commented on src/client/components/media-card/media-card/media-card.tsx
> +      <div
Afaik it has always just been the image that functioned as a button, but maybe it is suppose to be the whole card?

Need to ask Kevin/Steen if it should be whole card, or only the image as currently.
Have create a task for that. (https://tv2cms.atlassian.net/browse/UT-247)

2023-07-13 10:40 UTC, RasmusAlbrektsen approved these changes

2023-07-13 10:41 UTC, andr9528 commented on src/client/services/backend-observer.ts
> +        oldtime: [number, number],
That comment description is incorrect.

The first number is the total duration. The second number is the elapsed duration.
That information might also mean that `TimeRange`, is not the propper name for it.

2023-07-13 13:15 UTC, KvelaGorrrrnio commented on src/client/services/backend-observer.ts
> +        oldtime: [number, number],
It was at least helpful in uniting us in a common understanding. I agree that TimeRange is not the correct name for the type then.
Another way to express and make it more explicit is to map the type, when receiving it from CasparCG. The mapped format could be something like:
```typescript
interface MediaTimeMetadata {
  duration: number,
  elapsedTime: number,
}
```

I don't know if `MediaTimeMetadata` is the best name for it, but probably better than

2023-07-14 11:17 UTC, merged