UT-214: Clear file/folder paths targeting invalid paths
tv2/casparcg-cliptool pull request #86
Opened 2023-05-26 10:13 UTC by andr9528

I'd highly suggest to read the comments on the task as well, for some more insigt into the process/reasoning being the changes.

2023-05-31 16:00 UTC, KvelaGorrrrnio reviewed
I am not entirely sure what this fixes – so please enlighten me :smile:

2023-05-31 16:00 UTC, KvelaGorrrrnio commented on src/model/services/settings-service.ts
> +        const pathExist = allFiles.find((file) => {
`pathExist` conveys that this is a boolean, but it is `MediaFile | undefined`.

2023-05-31 16:00 UTC, KvelaGorrrrnio commented on src/server/handlers/caspar-cg-handler.ts
> +    await pollThumbnailChanges()
Why shouldn't we pollFileChanges?

2023-05-31 16:00 UTC, KvelaGorrrrnio commented on src/server/handlers/caspar-cg-handler.ts
> +                pollThumbnailChanges().then(() => {
Are these required to be executed sequentially?

2023-05-31 16:00 UTC, KvelaGorrrrnio commented on src/server/handlers/caspar-cg-handler.ts
> +                })
If either of the `pollX` calls fail, then `waitingForCcgResponse` will be true for the remainder of the program. And the rejected promise won't be caught.

2023-05-31 16:00 UTC, KvelaGorrrrnio commented on src/model/services/settings-service.ts
> +    public fixInvalidUsedPaths(
What is this function trying to solve?

2023-05-31 16:00 UTC, KvelaGorrrrnio commented on src/server/handlers/caspar-cg-handler.ts
> +            `Expected '${state.settings.ccgConfig.channels.length}' Outputs but had '${outputs.length}'`
Why are the numbers in single-quotes?

2023-05-31 16:00 UTC, KvelaGorrrrnio commented on src/server/handlers/caspar-cg-handler.ts
> +function extractFilesToOutputs(allFiles: MediaFile[]): void {
It does not look like this is being extracted, but rather that the _media_ files are merged into the outputs.

2023-05-31 16:00 UTC, KvelaGorrrrnio commented on src/server/handlers/caspar-cg-handler.ts
> +                }
There are a number of syntactical and performance optimizations that can be applied here. If you extract the output folder before doing the filter, there will be a lot less lookups for the output folder. If you apply that along with using shorthand notation it becomes:
```typescript
            const outputFolder = settingsService.getOutputSettings(state.settings, channelIndex).folder
            const outputMedia = thumbnails.filter(thumbnail => isFolderNameEqual(thumbnail.name, outputFolder))
```

2023-05-31 16:00 UTC, KvelaGorrrrnio commented on src/server/handlers/caspar-cg-handler.ts
> +    const fixedPaths = settingsService
What does it mean to fix? And what is a fixed path?

2023-07-05 08:25 UTC, andr9528 commented
> I am not entirely sure what this fixes – so please enlighten me 😄

@KvelaGorrrrnio If Cliptool has selected / cued a file for playing, that is then deleted regardless of if Cliptool is running or not, the targeted file will remain in the settings file, even though it is technically an invalid target now.
This PR fixes this by checking if the targeted file/folders exist when Cliptool boots. If the file/folder doesn't exist Cliptool remvoves the invalid reference in the settings file.

Now that i think of it, the code that does that cleanup, should propably also be run if the media files change, to clear the settings file of the invalid path, should a file be deleted that Cliptool has set to run / cue while running.

Might not be critical to clear the invalid target at the moment, but i could see it being an issue, if not fixed before UT-234, as CasparCG might be asked to play a non-existant file.

2023-07-05 09:05 UTC, andr9528 commented on src/server/handlers/caspar-cg-handler.ts
> +                pollThumbnailChanges().then(() => {
Not entirely sure, but i don't think so.
Have changed the function given to the interval to be async, and used await instead,

Also then moved setting `waitingForCcgResponse` to false to just after the awaits.
That should afaik ensure it gets set to false, even if the awaited ones fails somehow.

2023-07-05 09:08 UTC, andr9528 commented on src/server/handlers/caspar-cg-handler.ts
> +    await pollThumbnailChanges()
Hmm, i think i had some reasoning for it, but can't fully remember what. 
Have re-added polling for file changes, followed by the existing code.

2023-07-05 09:09 UTC, andr9528 commented on src/server/handlers/caspar-cg-handler.ts
> +                })
Afaik the changes made for the follow comment, should fix this.
https://github.com/tv2/casparcg-cliptool/pull/86/files#r1252793629

2023-07-05 09:13 UTC, andr9528 commented on src/server/handlers/caspar-cg-handler.ts
> +            `Expected '${state.settings.ccgConfig.channels.length}' Outputs but had '${outputs.length}'`
A bad habbit of mine. Gone now.

2023-07-05 09:17 UTC, andr9528 commented on src/server/handlers/caspar-cg-handler.ts
> +                }
Have applied the suggested changes here, and in one other similar place.

2023-07-05 09:20 UTC, andr9528 commented on src/model/services/settings-service.ts
> +        const pathExist = allFiles.find((file) => {
Renamed to `mediaFile`.

2023-07-05 09:24 UTC, andr9528 commented on src/model/services/settings-service.ts
> +    public fixInvalidUsedPaths(
It clears `cuedFileName`, `selectedFileName` and `folder` on an `outputSettings`, if they target a file/folder that doesn't exist any longer, i.e it clears invalid targeted paths, which it has now been renamed to better describe (`clearInvalidTargetedPaths(...)`).

2023-07-05 09:29 UTC, andr9528 commented on src/server/handlers/caspar-cg-handler.ts
> +function extractFilesToOutputs(allFiles: MediaFile[]): void {
Hmm, it extractes the files from the folder matching the one the output is configred for, and assign them to the specific output.

If it didn't do the filtering, then i'd agree that it just merges, but that is not the case.

2023-07-05 09:32 UTC, andr9528 commented on src/server/handlers/caspar-cg-handler.ts
> +    const fixedPaths = settingsService
An `outputSettings` with `fixedPaths` no longer points to files/folders that have been deleted.

 Have renamed the constant to `outputSettingsWithfixedPaths`, not sure if that helps, or is a sign that something needs to be reworked.

2023-07-07 08:46 UTC, KvelaGorrrrnio commented on src/server/handlers/caspar-cg-handler.ts
> +                })
The change you reference does not fix the issue. You still have a sequence of statements, where the sequence will prematurely abort if one step fails.
Since `waitingForCcgResponse` is the last statement, it will not be executed in case of failure from either of the previous statements. 
And in the case of failure, the rejected promise will not be caught. That is still something

The right approach would be to use finally syntax, either via Promise handling or try-catch-finally handling. It will solve both issues.

2023-07-07 09:36 UTC, KvelaGorrrrnio requested changes

2023-07-07 09:36 UTC, KvelaGorrrrnio commented on src/server/handlers/caspar-cg-handler.ts
> +            waitingForCcgResponse = false
It would be nice if `Ccg` was written out.

2023-07-07 09:36 UTC, KvelaGorrrrnio commented on src/server/handlers/caspar-cg-handler.ts
> +                })
The change you reference does not fix the issue. You still have a sequence of statements, where the sequence will prematurely abort if one step fails.
Since `waitingForCcgResponse = false` is the last statement, it will not be executed in case of failure from either of the previous statements. 
And in the case of failure, the rejected promise will not be caught. That is still something

The right approach would be to use finally syntax, either via Promise handling or try-catch-finally handling. It will solve both issues.

2023-07-07 09:36 UTC, KvelaGorrrrnio commented on src/server/handlers/caspar-cg-handler.ts
> +    const outputMedia = allFiles.filter(
Aren't these Media Files just like the ones stored in `mediaFiles`? If yes, then this should be `outputMediaFiles`.

And `mediaFiles` is defined as `output.mediaFiles`, then what is the difference?

2023-07-07 09:36 UTC, KvelaGorrrrnio commented on src/server/handlers/caspar-cg-handler.ts
> +function outputExtractFiles(
The function name seems a bit odd. Are we outputting the function extractFiles? And what does output mean in this context? Is it printing/logging or emitting some data or something third?

2023-07-07 09:36 UTC, KvelaGorrrrnio commented on src/server/handlers/caspar-cg-handler.ts
> +    const outputSettingsWithfixedPaths = new ReduxSettingsService()
`fixed` should be uppercased.

2023-07-07 09:36 UTC, KvelaGorrrrnio commented on src/server/handlers/caspar-cg-handler.ts
> +    }
You can invert the condition to make it a guard, which will remove an execution scope.
And if you extract the logic out into their own functions, this function will be easier to read and understand.

2023-07-07 09:36 UTC, KvelaGorrrrnio commented on src/shared/services/redux-settings-service.ts
> +        return outputSettings
Extracting the logic and relevant conditions out into appropriately named methods, will make the flow of this function more digestable.

2023-07-07 09:36 UTC, KvelaGorrrrnio commented on src/server/handlers/caspar-cg-handler.ts
> +    setInterval(async () => {
Just a note: Currently we setup an interval here, but the handle created is not stored, so we have no way of clearing the interval. And if we call this function multiple times, we will get a lot of unnecessary work to do.

2023-07-07 09:36 UTC, KvelaGorrrrnio commented on src/server/handlers/caspar-cg-handler.ts
>      }
Just a small optimization: This can be changed into a guard.
```suggestion
    if (!newThumbnails.hasChanges) {
        return
    }
    thumbnails = newThumbnails.thumbnails
    assignThumbnailsToOutputs()
```

2023-07-07 09:36 UTC, KvelaGorrrrnio commented on src/server/handlers/caspar-cg-handler.ts
> +    await loadFileList()
Should there be checked for changes in the files loaded, like for thumbnails?

2023-07-07 09:36 UTC, KvelaGorrrrnio commented on src/server/handlers/caspar-cg-handler.ts
> +async function pollThumbnailChanges(): Promise<void> {
Just a note: `poll` seems to say the same as `get` in this context. Poll might points toward long-polling, which is not the case here.

2023-07-07 09:36 UTC, KvelaGorrrrnio commented on src/server/handlers/caspar-cg-handler.ts
> +                pollThumbnailChanges().then(() => {
One could bundle the promises, and await both with `Promise.all`. But I don't think it is necessary for that optimization. So I'll resolve this conversation. I have commented on the relevant comment regarding `waitingForCcgResponse` begin set to false.

2023-07-07 09:36 UTC, KvelaGorrrrnio commented on src/server/handlers/caspar-cg-handler.ts
> +                isFolderNameEqual(thumbnail?.name, outputFolder)
Why is optional chaining use here? When will a thumbnail not have a name?

2023-07-07 09:36 UTC, KvelaGorrrrnio commented on src/server/handlers/caspar-cg-handler.ts
> +            const outputThumbnailList = output.thumbnailList
Why is this stored in a local variable?

2023-07-07 09:36 UTC, KvelaGorrrrnio commented on src/server/handlers/caspar-cg-handler.ts
> +    const mediaFiles = output.mediaFiles
Why is this stored in a local variable?

2023-07-11 07:38 UTC, andr9528 commented on src/server/handlers/caspar-cg-handler.ts
> +                })
Moved the awaits into a try, and the reset of boolean into a finally.

2023-07-11 07:39 UTC, andr9528 commented on src/server/handlers/caspar-cg-handler.ts
> +            waitingForCcgResponse = false
Done.

2023-07-11 07:44 UTC, andr9528 commented on src/server/handlers/caspar-cg-handler.ts
> +    const outputMedia = allFiles.filter(
`output.mediaFiles` contains what we currently have, and `outputMedia` (now `outputMediaFiles`) contains the new versions of the files.

If they are different, then the new ones overwrite the old ones.

Have removed saving of `output.mediaFiles` to a new constant.

2023-07-11 07:45 UTC, andr9528 commented on src/server/handlers/caspar-cg-handler.ts
> +function outputExtractFiles(
Renamed to `extractFilesToOutput`.

2023-07-11 07:45 UTC, andr9528 commented on src/server/handlers/caspar-cg-handler.ts
> +    const outputSettingsWithfixedPaths = new ReduxSettingsService()
Fixed.

2023-07-11 08:21 UTC, andr9528 commented on src/server/handlers/caspar-cg-handler.ts
> +    }
Have inverted it, and extracted the innards of the if to a new function called `saveFixedPathsSettings`.

2023-07-11 08:27 UTC, andr9528 commented on src/shared/services/redux-settings-service.ts
> +        return outputSettings
Have done that now.

2023-07-11 08:31 UTC, andr9528 commented on src/server/handlers/caspar-cg-handler.ts
>      }
Done

2023-07-11 08:32 UTC, andr9528 commented on src/server/handlers/caspar-cg-handler.ts
> +async function pollThumbnailChanges(): Promise<void> {
Have renamed them to say `get` instead.

2023-07-11 08:42 UTC, andr9528 commented on src/server/handlers/caspar-cg-handler.ts
> +    setInterval(async () => {
This timeout should now have logic to ensure that only one instance of the timeout runs.

Unsure if something similar should be done for the timeout in the `startTimeEmitInterval` function.
And if so, how about the subscribtion to the `reduxStore`?

2023-07-11 08:44 UTC, andr9528 commented on src/server/handlers/caspar-cg-handler.ts
> +            const outputThumbnailList = output.thumbnailList
It isn't any longer :P

2023-07-11 08:45 UTC, andr9528 commented on src/server/handlers/caspar-cg-handler.ts
> +    const mediaFiles = output.mediaFiles
It isn't any longer :P

2023-07-11 08:45 UTC, andr9528 commented on src/server/handlers/caspar-cg-handler.ts
> +                isFolderNameEqual(thumbnail?.name, outputFolder)
I think that was a leftover from before refactor.
Have removed it now, with no ill effect from what i can tell.

2023-07-11 08:51 UTC, andr9528 commented on src/server/handlers/caspar-cg-handler.ts
> +    await loadFileList()
Afaik, those checks are done further down the call stack.

2023-07-11 11:38 UTC, KvelaGorrrrnio requested changes
Changes looks fine, there are a few things that needs to be changed :)

2023-07-11 11:38 UTC, KvelaGorrrrnio commented on src/server/handlers/caspar-cg-handler.ts
> +    if (changesTimeout) {
Timeout indicates that it is a single-off effect. So since we are storing an interval in this, it could be named either `fileChangesInterval` or `fileChangesTimer`.

2023-07-11 11:38 UTC, KvelaGorrrrnio commented on src/shared/services/redux-settings-service.ts
> +        }
There should not be paths referencing the specifics of your local environment.

Don't we have a type for outputSettings? In the unlikely case that we don't have a type for it, then this function is only dependent on the type `{ folder: string }`.

2023-07-11 12:43 UTC, andr9528 commented on src/server/handlers/caspar-cg-handler.ts
> +    if (changesTimeout) {
Renamed to `fileChangesInterval`.

2023-07-11 12:44 UTC, andr9528 commented on src/shared/services/redux-settings-service.ts
> +        }
I have no idea why it was imported that way. Has been fixed.

2023-07-11 12:47 UTC, andr9528 commented on src/shared/services/redux-settings-service.ts
> +        }
I think i know how it happend. I had VS Code generate the function for the, which is propably why.

2023-07-11 12:50 UTC, andr9528 commented on src/server/handlers/caspar-cg-handler.ts
> +    const outputSettingsWithfixedPaths = new ReduxSettingsService()
Completely by accident btw.

2023-07-13 07:04 UTC, KvelaGorrrrnio approved these changes

2023-07-13 07:04 UTC, KvelaGorrrrnio commented on src/server/handlers/caspar-cg-handler.ts
>          }
The if statement can be made into a guard
```suggestion
        if (waitingForCasparcgResponse) {
            return
        }
        waitingForCasparcgResponse = true
        try {
            await getFileChanges()
            await getThumbnailChanges()
        } finally {
            waitingForCasparcgResponse = false
        }
```

2023-07-13 07:04 UTC, KvelaGorrrrnio commented on src/shared/services/redux-settings-service.ts
> +        mediaState: Media
When I read the type `Media` I expect it to be related to e.g. the contents of a media file or some metadata descriptor about it. I have to look at the parameter name to understand what it is that I am looking at. Perhaps the `Media` type should be renamed to `MediaState`.

2023-07-13 07:27 UTC, andr9528 commented on src/server/handlers/caspar-cg-handler.ts
>          }
Done

2023-07-13 07:41 UTC, RasmusAlbrektsen approved these changes
Just one question, looks good :-)

2023-07-13 07:41 UTC, RasmusAlbrektsen commented on src/server/handlers/caspar-cg-handler.ts
> +                isFolderNameEqual(thumbnail.name, outputFolder)
This might just be a personal opinion, but from the name `isFolderNameEqual`, i'm not entirely sure what this does. Is this having two equal folder names or that the thumbnail name equals the folder name? 
I couldn't trace the method over github for some reason.

2023-07-13 07:51 UTC, andr9528 commented on src/server/handlers/caspar-cg-handler.ts
> +                isFolderNameEqual(thumbnail.name, outputFolder)
The `thumbnail.name` is the full path of the file that the thumbnail is for, with CasparCG's media folder as the base.
The `outputFolder` is the folder we want thumbnails for.
The function checks if the thumbnail is located in the folder we want thumbnails for.

Hope this clarifies it. Not sure if the function needs a new name.

2023-07-13 08:08 UTC, RasmusAlbrektsen commented on src/server/handlers/caspar-cg-handler.ts
> +                isFolderNameEqual(thumbnail.name, outputFolder)
I think my confusions stems from the fact that `thumbnail.name` is actually a path to it's file, at not the actual file name/thumbnail name.

2023-07-17 07:57 UTC, merged